"""Roadmap v4: Orb v1 Live Tyre Intelligence -> out/Orb_v1_Roadmap_v5.pdf and out/ROADMAP_v5.md"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
ss = getSampleStyleSheet()
H1 = ParagraphStyle('H1', parent=ss['Heading1'], fontSize=16.5, leading=20, spaceBefore=8, spaceAfter=7)
H2 = ParagraphStyle('H2', parent=ss['Heading2'], fontSize=12, spaceBefore=8, spaceAfter=4)
B = ParagraphStyle('B', parent=ss['BodyText'], fontSize=9.8, leading=13.6, spaceAfter=5)
SM = ParagraphStyle('SM', parent=B, fontSize=8.4, leading=11, textColor=colors.HexColor('#4B5563'))
BUL = ParagraphStyle('BUL', parent=B, leftIndent=12, bulletIndent=2, spaceAfter=2.5)
MONO = ParagraphStyle('MONO', parent=B, fontName='Courier', fontSize=8, leading=10.2, leftIndent=8, spaceAfter=4)
CELL = ParagraphStyle('CELL', parent=B, fontSize=8.1, leading=10.3, spaceAfter=0); CELLB = ParagraphStyle('CELLB', parent=CELL, fontName='Helvetica-Bold')
def P(t, s=B): return Paragraph(t, s)
def bullets(items): return [Paragraph(t, BUL, bulletText='•') for t in items]
def table(rows, widths):
    data = [[Paragraph(str(c), CELLB if i == 0 else CELL) for c in r] for i, r in enumerate(rows)]
    t = Table(data, colWidths=widths, repeatRows=1); t.setStyle(TableStyle([('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#C7CCD4')), ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E5E7EB')), ('VALIGN', (0, 0), (-1, -1), 'TOP'), ('LEFTPADDING', (0, 0), (-1, -1), 4), ('RIGHTPADDING', (0, 0), (-1, -1), 4), ('TOPPADDING', (0, 0), (-1, -1), 3), ('BOTTOMPADDING', (0, 0), (-1, -1), 3)])); return t
MD = []
def md(t): MD.append(t)
S = [Spacer(1, 1.2 * cm), P('Orb v1 Live Tyre Intelligence: roadmap v5', ParagraphStyle('T', parent=ss['Title'], fontSize=25, leading=30, alignment=0)),
     P('Predict. Monitor. Decide. Prove.', ParagraphStyle('TG', parent=B, fontSize=14, leading=18, textColor=colors.HexColor('#111827'))),
     P('A pre-race and real-time tyre-performance intelligence system with driver feedback, sensor-ready live estimation, risk-aware pit recommendations and Race Twin validation.', ParagraphStyle('ST', parent=B, fontSize=11.5, leading=16, textColor=colors.HexColor('#374151'))),
     Spacer(1, 6), P('Team Orb v1 &middot; Product Orb v1 (internal codename Orb v1) &middot; Core: Degradation Intelligence Engine &middot; Modes: Live Predictor, Ghost Strategy &middot; Feature: Race Twin &middot; TrackShift 2026 &middot; v5 issued 12 September 15:20 IST as the build contract.', SM), Spacer(1, 10)]
md('# Orb v1 Live Tyre Intelligence: roadmap v5\n\n*Predict. Monitor. Decide. Prove.* Build contract, 12 Sep 15:20 IST.\n')
# ---------- 0 ----------
S += [P('0. What Orb v1 is', H1),
      P('<b>Naming, final.</b> Team: Orb v1 (registered with the organisers as FireBolt). Product: Orb v1. Core: Degradation Intelligence Engine. Mode 1: Live Predictor. Mode 2: Ghost Strategy. Feature inside Ghost Strategy: Race Twin. The idea-round submission was titled ClearStint; one line in the deck says so. Dashboard header: ORB V1 | Live Tyre Intelligence | Team Orb v1 &middot; TrackShift 2026.', SM),
      P('<b>Orb v1 contains two independent modes powered by one degradation-intelligence core.</b> Live Predictor begins with a locked pre-race forecast, updates the tyre state from information available during the race and recommends when to pit and which tyre to fit. Ghost Strategy is a post-race audit and counterfactual analysis environment that tests the same frozen forecast across drivers, circuits and supported weather regimes, then visualises how alternative tyre choices propagate through the race. For the jury: <i>Live Predictor is the operational product. Ghost Strategy is the audit laboratory. The first makes the call; the second shows whether the model deserved to make it.</i>'),
      P('In more detail. Before the race, it estimates compound-specific degradation distributions and recommends strategy and pit windows from practice, historical, weather and circuit data. During the race, it fuses corrected pace, live telemetry, track conditions, traffic, structured driver feedback and private tyre sensors when available to update a probabilistic tyre-performance state every lap. It forecasts remaining operational tyre life and cliff risk, then ranks pit and compound actions by expected race-time benefit and downside. Race Twin is the proof-and-explanation layer: it replays alternative tyre choices, exposes how each prediction affects the race and connects the model to its held-out validation. Public-data mode operates with wider uncertainty; team-data mode replaces assumptions with direct measurements and tightens the same model.'),
      P('The verified core is untouched: one lock as the source of truth, the stint fixed-effects estimator, exact strategy enumeration, compound offsets, pit-loss handling, the post-race replay, and the 11-weekend, 29-case evidence base (0.023 against 0.137 s/lap, 28 of 29). Everything below is layered on top through interfaces, so a component can fail without taking the product with it.', SM),
      P('0.1 Six capabilities, feasibility verdicts', H2),
      table([['Capability', 'Verdict', 'Correct implementation', 'Reality check'],
             ['Driver in the loop', 'Yes, core feature', 'Timestamped, structured observation with uncertainty that shifts regime probabilities; never a direct seconds adjustment; the engineer enters or confirms it, the driver never touches a screen', 'Calibration profiles per driver need history; today the form, log, audit and regime update are built, calibration is Phase 2'],
             ['Live tyre telemetry', 'Yes, in team mode', 'Public mode ingests timing, car data, gaps, weather, radio records and derived proxies; team mode adds pressures, temperatures, slip, steering, fuel, set identity through the same adapter interface', 'The 2026 regulations mandate tyre pressure and temperature sensors on every car, but those channels are not public. Public live data: FastF1\'s live-timing recorder is free and must run during the session; OpenF1 real-time is a paid tier, its history is free with a delay'],
             ['Historical versus live trend', 'Yes, the main screen', 'Pre-race prior band, live corrected observations, live posterior curve, comparable historical stints, 1-3-5-10-lap forward prediction, cliff probability, crossover', 'Demonstrated as replay today; genuinely live for the Madrid race on Sunday evening, after the event, through the recorded-live source'],
             ['Pre-race tyre strategy', 'Already present', 'Expand from one best plan to probability-ranked pit windows and alternatives with expected gain, downside and the condition that flips the call', 'One to two hours; the enumeration exists'],
             ['Live pit and tyre recommendation', 'Yes, the main decision output', 'Re-run the optimiser after every relevant event; ranked actions with gain, probability, downside, rejoin context, evidence, and which observation changed the call', 'Rejoin and traffic estimation is Phase 1; in Phase 0 the rejoin context is the observed gap structure'],
             ['Driver degradation profile', 'Yes, but hardest', 'Style profile from telemetry plus outcome profile as conditional residuals under hierarchical shrinkage with teammate-within-weekend comparisons; cross-track prediction with wide intervals', 'Phase 2: needs three seasons and leave-one-circuit-out and leave-one-season-out validation; never a raw ranking']], [2.6 * cm, 2.1 * cm, 6.3 * cm, 5.8 * cm])]
md('## 0. Orb v1\nPre-race prior -> live posterior every lap (telemetry, conditions, traffic, driver feedback, private sensors when available) -> useful life and cliff risk -> ranked pit/compound actions -> Race Twin proof. Six capabilities: all feasible; live telemetry in team mode; driver profile hardest (Phase 2).\n')
# ---------- 1 architecture ----------
S += [P('1. Architecture and components', H1),
      P('Practice and historical data -> pre-race tyre and strategy prior -> live timing, telemetry, weather, traffic + structured driver feedback + private tyre sensors when available -> probabilistic live tyre-state estimator -> live degradation curve and remaining-useful-life forecast -> exact strategy and pit-window optimiser -> ranked action list with expected gain, uncertainty and reasons -> Race Twin and post-race scorecard.', MONO),
      P('Shared Degradation Intelligence Core (practice + history + weather + driver context) -> frozen pre-race forecast snapshot -> LIVE PREDICTOR MODE (race-time decision support)  |  GHOST STRATEGY MODE (post-race audit and analysis). The same pre-race model powers both. Neither mode depends on the other.', MONO),
      P('shared/: PreRaceCurveProvider, DegradationFeaturePipeline, StrategyCostModel, ModelRegistry, ForecastSnapshot.  live/: LiveTyreStateEstimator, LiveStrategyRecommender, DriverFeedbackAdapter, TelemetryAdapter, RaceEventSource.  ghost/: GhostStrategyEngine, CounterfactualEngine, HistoricalAudit, ScenarioExplorer, RaceTwinRenderer.  Allowed: live -> shared, ghost -> shared.  Forbidden: live -> ghost, ghost -> live state. Enforced by an import-boundary test, not by documentation.', MONO),
      P('Live data boundary, enforced in code: the live mode reads only the pre-race forecast, completed laps, current telemetry, current weather, traffic and gaps, driver feedback and team sensors if connected; it can never read future laps, final results, post-race reference curves, Ghost Strategy outcomes or the hindsight-optimal strategy. Every live state asserts data_cutoff <= event_timestamp, uses_future_data is False, uses_post_race_reference is False.', SM),
      P('Live model of record: a robust regime-switching Bayesian state-space model (latent thermal state, performance-wear state, grip loss, degradation rate, cliff hazard, anomaly probability; regimes WARMUP, NORMAL, OVERHEATING, GRAINING, RECOVERING, ACCELERATING_WEAR, CLIFF, ANOMALY) with explicit process noise so the band can widen, a boosted residual model for systematic error, and the exact optimiser. The liquid network is at most an optional high-frequency thermal encoder, kept only if it beats hand features and an exponentially weighted proxy on held-out races. The buildable Phase 0 version of the estimator is linear-Gaussian with fixed regime rules; the full regime switching is Phase 1.', SM)]
md('## 1. Architecture\nPreRaceCurveProvider, LiveTyreStateEstimator, StrategyOptimizer, RaceTwinEngine + adapters + RaceEventSource. Live model: regime-switching Bayesian state-space with process noise, boosted residual, exact optimiser; LNN optional encoder only.\n')
# ---------- 2 sittings ----------
S += [P('2. Sittings and anchors', H1),
      table([['Sitting', 'When (IST)', 'Scope', 'Anchors'],
             ['1 (now)', 'Sat 14:15 to 23:30', 'Phase 0: Race Twin vertical slice plus the live vertical slice on replay, sealed holdout, contracts, provider abstraction; parallel non-blocking model and feature work', 'Madrid FP3 refresh 17:30; qualifying refresh and hashed forecast 20:45; timed rehearsal 22:30'],
             ['2', 'Sun 05:30 to the slot, then evening', 'Phase 1 subset before the slot: all drivers of one race, live-prefix evaluation aggregate, decision board, driver-feedback demo, two rehearsals; rest after the slot', 'Smoke test 08:00; presentation; Madrid race 18:30 live through the recorded-live source; scorecard'],
             ['3', 'After the event', 'Phase 2: profiles, regime model, absolute compounds, sensor adapters, documents', 'Publish the scorecard beside the pre-race hash']], [1.7 * cm, 3 * cm, 7.4 * cm, 4.7 * cm]),
      P('Three-season download: about 253 of 350 sessions on disk at 13:35, five workers still running, automatic cleanup pass queued; complete by about 15:15. Heavy workstreams are limited to four concurrent processes until then.', SM)]
md('## 2. Sittings\n1: Sat 14:15-23:30 Phase 0 with Madrid anchors. 2: Sun pre-slot subset of Phase 1, rest after. 3: post-event Phase 2.\n')
# ---------- 3 phase 0 ----------
S += [PageBreak(), P('3. Phase 0, this sitting: two vertical slices', H1),
      P('Phase 0 is complete when two <b>independent</b> vertical slices work on the same historical event and reference the same forecast hash. <b>Ghost Strategy:</b> select event, driver, actual weather context, intervention lap and compound; load the frozen pre-race forecast; produce the post-race audit, the counterfactual race, uncertainty and the ghost replay, with the live estimator disabled. <b>Live Predictor:</b> load the same frozen forecast; replay the event one lap at a time; update the tyre-state posterior; compare live performance against the prior; accept structured driver feedback; update the ranked pit recommendation, with the counterfactual engine disabled. The live workflow never opens Ghost Strategy; after a race completes it may offer a navigation link, nothing more.'),
      table([['#', 'Task', 'Owner', 'Accepted when'], ['0.0', 'Automated acceptance suite (pytest) created before any feature: import-boundary test, data-cutoff assertions, identity and conservation tests, forecast-hash equality across modes, replay-cannot-see-lap-k+1 test; runs on every merge', 'Workstream 7', 'Suite exists and fails loudly on a deliberate violation']], [0.9 * cm, 8.9 * cm, 1.6 * cm, 5.4 * cm]),
      P('3.1 Mandatory, Ghost Strategy slice', H2),
      table([['#', 'Task', 'Owner', 'Accepted when'],
             ['0.1', 'Seal the holdout before anything is tuned with the one rule used everywhere: holdout_count = clamp(round(0.18 x eligible_weekends), 4, 6); eligible = 2023 to 2025 weekends with complete practice and race files passing feed-quality rules at seal time; metadata-only selection with one weekend per available season, one street circuit, one high- and one low-degradation circuit, hot and cool dry where available, one SC or VSC race scored separately, no circuit twice; seed 2026; sealed_holdout_manifest.json and .sha256 committed; the evaluator refuses per-race reveal until freeze.json says model, feature list, gate threshold and provider are frozen with a git commit; later tuning is post_holdout_tuning', 'Workstream 3', 'prohibited_for_tuning true; selection reproducible'],
             ['0.2', 'Minimal lock v2: pydantic models, JSON schema, additionalProperties false in stable blocks, extensions namespace, v1 adapter, golden fixtures, atomic writes, sidecars by hash; new blocks input_availability, pre_race_forecast, live_tyre_state, driver_feedback_events, live_recommendations, driver_profile, counterfactuals, validation', 'Workstream 1', 'Downstream workstreams work from the fixture; schema test on merge; no large arrays in the lock'],
             ['0.3', 'PreRaceCurveProvider with the current estimator as provider A', 'Workstream 2', 'Reproduces the v1 curves exactly'],
             ['0.4', 'Counterfactual core, fixed-context and tyre-only: decomposition Y = B + T + P + I + e; standardised pit event as a distribution; SC and VSC as fixed observed schedule with SC pit loss and frozen pace gains; contaminated laps reconstructed', 'Workstream 2', 'Identity, same-compound, no-degradation, round-trip and time-accounting tests pass; scenario under 250 ms'],
             ['0.5', 'Track geometry and time-warped two-blip player with Plotly fallback; uncertainty by whole-curve sampling with precomputed quantiles', 'Workstream 4', 'Actual-plan ghost overlays the driver; frame rate offline; quantiles ordered'],
             ['0.6', 'Ghost Strategy routes in the existing dashboard: Historical Audit (frozen forecast, actual weather, post-race reference, forecast error, coverage, actual and recommended strategy, hidden-stop result, regret, ghost animation), with Scenario Explorer and Generalisation Scorecard stubs marked model-implied and pending', 'Workstream 6', 'Under two seconds; offline; audit versus scenario clearly labelled']], [0.9 * cm, 8.9 * cm, 1.6 * cm, 5.4 * cm]),
      P('3.2 Mandatory, Live Predictor slice', H2),
      table([['#', 'Task', 'Owner', 'Accepted when'],
             ['0.7', 'Live-state contract: live_tyre_state and live_recommendation schemas; every value timestamped and online-safe', 'Workstream 1', 'Schema test passes; no field can carry future data'],
             ['0.8', 'Replay state estimator: lap-by-lap posterior update from the pre-race prior (linear-Gaussian, explicit process noise, resets at stops, widening rules for rain, temperature shifts, push changes, SC cooling, feed degradation, out-of-support)', 'Workstream 8', 'No future data; batch and replay results agree; band widens on the listed triggers'],
             ['0.9', 'RaceEventSource: replay and recorded-live sources emitting position_update, lap_completed, pit_entry, pit_exit, weather_update, track_status, overtake, retirement, feed_quality_warning', 'Workstream 2', 'Model and dashboard cannot tell which source is active'],
             ['0.10', 'Driver-feedback input: structured engineer form and event log (timestamp, lap, axle, corner phase, symptom, severity, trend, confidence, source, raw message, engineer confirmation); feedback shifts regime probabilities, never adds seconds directly; can be enabled, disabled, audited', 'Workstream 8', 'Feedback effect visible on the posterior and reversible'],
             ['0.11', 'Live comparison graph: prior band, corrected observations, posterior curve, comparable historical stints, 1-3-5-10-lap forward prediction, cliff probability, crossover', 'Workstream 6', 'Updates per event without retraining or page reload'],
             ['0.12', 'Action engine: optimiser re-run per event; ranked actions with expected gain, probability, downside, target compound and set, rejoin context, evidence, and change_reason naming the observation that moved the call', 'Workstream 8', 'Every recommendation carries gain, risk and explanation; recommendation history logged'],
             ['0.13', 'Red team on both slices; anchors: Madrid FP3 refresh, qualifying refresh, hashed forecast, deck slide, timed run', 'Workstream 7, Lead', 'blocking_issues.json empty; hash before 21:45']], [0.9 * cm, 8.9 * cm, 1.6 * cm, 5.4 * cm]),
      P('Phase 0 acceptance tests', H2)] + bullets(['Ghost works without LiveTyreStateEstimator.', 'Live works without GhostStrategyEngine.', 'Both use the same pre-race forecast hash.', 'Live cannot read post-race reference fields.', 'Ghost clearly identifies historical audit versus scenario exploration.', 'Changing nothing in Ghost produces zero delta.', 'Replay live mode never sees lap k+1 while processing lap k.']) + [
      P('3.3 Parallel, non-blocking', H2)] + bullets(['Weather-only feature pass: per-lap track and air temperature, deltas, humidity, wind, rainfall, thermal proxy, load-dose split, run phases, used-set flag, "tyre demand index".', 'Errors-in-variables Friday-to-Sunday regression on three seasons, chronological evaluation, weekend bootstrap, risk-coverage, information gate; provider B only if it wins held out.', 'Downloads and cleanup.']) + [
      P('3.4 Not tonight', H2)] + bullets(['Full redesign of secondary views is deferred; the premium application shell and the Live Predictor and Ghost Strategy hero screens are mandatory in Phase 0 (tasks 0.14 to 0.17).', 'Driver profiles; TUMFTM; multi-agent simulation; any attempt to make the liquid network win.'])
md('## 3. Phase 0\nRace Twin slice (0.1-0.6) + live slice (0.7-0.13): live-state contract, replay estimator with widening, RaceEventSource, driver-feedback input, live comparison graph, action engine, red team, Madrid anchors.\n')
# ---------- 4 phase 1 ----------
S += [Spacer(1, 6), P('4. Phase 1, second sitting: operational live intelligence and validation', H1)] + bullets([
      'Live adapters: FastF1 live-timing recorder as the free public source, OpenF1 adapter where licensed, recorded-live fallback, team sensor adapter interface with clock synchronisation.',
      'Driver-feedback radio and manual adapter; available tyre-set inventory; live rejoin and traffic estimation; alert and recommendation history; prefix-based live validation.',
      'Race Twin at scale: all drivers of one race, then the sealed holdout, then every 2026 race; hidden-stop-response evaluation; strategy regret under a post-race reference; leave-one-driver-out audit; frozen-field simulator behind the fixed-context fallback with SC-neutral and SC-aware outputs.',
      'Dashboard: fidelity switch live, rival blips, position distributions, validation views, historical replay controls, the prospective Madrid case live through the recorded-live source on Sunday evening.',
      'Documents regenerated from lock v2; demo path rehearsed twice before the slot.'])
md('## 4. Phase 1\nLive adapters, feedback adapter, inventory, rejoin, histories, prefix validation; Race Twin scale and validation; frozen field behind fallback; dashboard integration; documents.\n')
# ---------- 5 phase 2 ----------
S += [P('5. Phase 2, third sitting: advanced generalisation', H1)] + bullets([
      'Driver style and outcome profiles with hierarchical shrinkage; cross-track prediction; driver-feedback calibration; teammate-within-weekend, leave-one-circuit-out, leave-one-season-out, test-retest, minimum evidence, cold start.',
      'Regime-switching state-space live estimator; boosted residual benchmark with weekend-grouped validation; cross-season and regulation-domain adaptation.',
      'Absolute C1 to C5 compound mapping; corner-specific thermal and load modelling; per-corner team-sensor mode; private-data sensor-fusion evaluation.',
      'Shape-constrained wear curve; better pit-loss and warm-up model; corner-weighted spatial delta; traffic interaction; TUMFTM comparison; multi-agent simulation last; liquid network only as an optional encoder.'])
md('## 5. Phase 2\nDriver profiles; regime-switching estimator; boosted residual; absolute compounds; sensor modes; shape-constrained wear; TUMFTM; multi-agent last.\n')
# ---------- 6 workstreams ----------
S += [P('6. Workstreams, ownership, integration', H1),
      table([['Workstream', 'Owns', 'Builds', 'Accepted when'],
             ['1 Contract and fixtures', 'schemas/, fixtures/, validators/', 'lock v2 incl. live blocks, fixtures, validator, v1 adapter', 'Downstream workstreams work from fixtures; no large arrays in the lock'],
             ['2 Counterfactual core and events', 'counterfactual/, events/', 'Decomposition, interventions, pit and SC rules, Monte Carlo, provider interface, RaceEventSource', 'Identity tests pass; scenario under 250 ms; sources interchangeable'],
             ['3 Blind evaluation', 'evaluation/', 'Sealed holdout, hidden-stop-response, regret, live-prefix evaluation, calibration, weekend bootstrap, scorecards', 'Builders cannot see per-race results; every metric weekend-grouped'],
             ['4 Geometry and animation', 'replay/, dashboard/components/', 'Canonical path, pit lane, time warping, browser player, fallbacks', 'Ghost overlays the driver; frame rate offline'],
             ['5 Frozen field', 'interaction/', 'Rival trajectories, following loss, overtake probability, position distribution', 'Observed plan reconstructs observed ordering; fallback exact'],
             ['6 Dashboard', 'app routes, views/', 'Pre-race plan, live tyre state (main), decision board, driver feedback, driver profile, Race Twin, validation', 'No training in the dashboard; every number from lock or hashed asset; under two seconds; offline'],
             ['7 Red team', 'none', 'red_team_report.json, blocking_issues.json, claim_evidence_map.json', 'No release with a blocking issue'],
             ['8 Live intelligence', 'live/, decision/', 'LiveTyreStateEstimator, DriverFeedbackAdapter, StrategyOptimizer re-run logic, action engine, recommendation history', 'No future data in replay; band widens on triggers; every action explained']], [2.6 * cm, 2.9 * cm, 6 * cm, 5.3 * cm]),
      P('Integration rules: directory ownership; validator, identity tests and release gates on every merge; numbers reach slides only through the lock; at most four heavy processes until the download finishes; a claim on a screen may not exceed the selected fidelity or sensor mode; the claim_scope and sensor_mode fields are rendered, not paraphrased.', SM)]
md('## 6. Workstreams\nEight workstreams by directory; gates on merge; claims bound to mode.\n')
# ---------- 7 contracts ----------
S += [PageBreak(), P('7. Contracts', H1),
      P('PreRaceCurveProvider.predict_curve(event, driver, compound, context, age_range) -> CurveDistribution(mean, q10, q50, q90, cliff_probability, provenance)', MONO),
      P('LiveTyreStateEstimator.update(prior_state, telemetry, context, driver_feedback=None, sensor_data=None) -> TyreStateDistribution', MONO),
      P('StrategyOptimizer.recommend(tyre_state, available_sets, race_context, competitor_context) -> RankedActions', MONO),
      P('DriverFeedbackAdapter.parse(feedback_event) -> FeedbackObservation;  DriverProfileProvider.predict(driver, circuit, compound, car_context, weather) -> DriverTyrePrior', MONO),
      P('RaceEventSource.events() -> RaceEvent; implementations Replay, Live, RecordedLive', MONO),
      P('7.0 Lock namespaces', H2),
      P('shared: forecast_snapshot, model_version, forecast_hash, training_cutoff, support_definition.  live_predictor: data_cutoff, prior, posterior, recommendations, driver_feedback, uses_future_data=false, uses_post_race_reference=false.  ghost_strategy: mode (historical_audit | scenario_explorer | generalisation_scorecard), event, driver, weather_context, forecast_snapshot_hash, race_reference, counterfactual, generalisation_status, model_implied=true.', MONO),
      P('Support fields on every Ghost Strategy result: track_seen_during_training, driver_seen_during_training, weather_in_training_range, compound_support, season_support, overall_support_status (IN SUPPORT | NEAR TRAINING SUPPORT | OUT OF SUPPORT, FORECAST WITHHELD), abstention_reason.', MONO),
      P('7.1 live_tyre_state fields', H2),
      P('lap, timestamp, compound, tyre_age, state_regime, corrected_pace_loss, degradation_rate, thermal_stress_index, performance_wear_index, useful_laps_q10, useful_laps_q50, useful_laps_q90, cliff_probability_3_laps, cliff_probability_5_laps, trend_vs_pre_race, confidence, sensor_mode (PUBLIC PROXY or TEAM SENSOR), support_status, sensor_availability, source_latency, missing_channels, quality_status', MONO),
      P('7.2 live_recommendation fields', H2),
      P('action, pit_window, target_compound, target_set, expected_gain_median, expected_gain_q10, expected_gain_q90, probability_of_gain, rejoin_context, reasons, constraints, changed_since_last_update, change_reason', MONO),
      P('7.3 driver feedback event', H2),
      P('timestamp, lap, axle (front, rear, all, unknown), corner_phase (braking, entry, mid, exit, traction), symptom (understeer, oversteer, sliding, graining, overheating, vibration, lack_of_grip), severity 1 to 5, trend, driver_confidence, source, raw_message, engineer_confirmed', MONO),
      P('Public mode never displays physical tread remaining, physical wear percentages or per-tyre structural health. It displays performance_loss, operational_useful_laps_remaining, thermal_stress_index and performance_wear_index. Every output carries sensor_availability, source_latency, missing_channels, quality_status and confidence_effect.', SM)]
md('## 7. Contracts\nFive interfaces; live_tyre_state, live_recommendation and driver feedback fields; public-mode display rules.\n')
# ---------- 8 dashboard ----------
S += [P('8. Dashboard structure', H1),
      P('Landing page: two doors. <b>Live Predictor</b>: compare live tyre behaviour against the locked pre-race forecast and receive updated pit and compound recommendations; buttons Start historical replay, Connect live feed, Load recorded-live session. <b>Ghost Strategy</b>: audit a completed race, test an alternative tyre strategy and inspect model generalisation across drivers, tracks and supported weather; buttons Historical audit, Scenario explorer, Generalisation scorecard. The user is never sent automatically from one to the other.'),
      table([['Route', 'Content'],
             ['1 Pre-race plan', 'Compound curves and bands, strategy tree, pit windows, one-stop versus two-stop probability, weather scenarios, driver-specific prior, tyre inventory'],
             ['2 Live Predictor (main screen)', 'Current compound and age; forecast versus live graph; degradation rate; trend versus expected; thermal and wear indices; useful laps remaining; cliff probability; data-quality and sensor-mode status'],
             ['3 Decision board', 'Top three actions with target compound and set, pit window, expected gain, downside, rejoin traffic, and why the recommendation changed'],
             ['4 Driver feedback', 'Structured entry, latest feedback, whether telemetry supports it, effect on posterior and recommendation, calibration history'],
             ['5 Driver profile', 'Style dimensions, context-adjusted degradation, track-class and compound behaviour, teammate comparison, confidence and evidence count (Phase 2)'],
             ['6 Ghost Strategy: Historical Audit', 'Frozen forecast before the selected race, actual historical weather, selected driver; race data only for scoring and reconstruction; forecast versus race-derived reference, error and coverage, actual versus recommended strategy, hidden-stop-response, regret, ghost animation. This page is evidence.'],
             ['6b Ghost Strategy: Scenario Explorer', 'Change temperature regime, weather scenario, compound, pit lap, set condition, driver. Banner: "Model-implied scenario. No observed outcome exists for this combination." Weather offered only as supported scenarios: actual historical, pre-race forecast snapshot, cooler dry, baseline dry, hotter dry, variable or damp only if supported, wet unavailable until a wet model validates; each with a support status'],
             ['6c Ghost Strategy: Generalisation Scorecard', 'Aggregate results over the sealed sample by cell: seen circuit and seen driver, unseen circuit and seen driver, seen circuit and held-out driver, hot dry, cool dry, variable, high and low degradation, street and permanent circuits'],
             ['7 Validation', 'Pre-race held-out accuracy, live next-lap and multi-lap accuracy, interval coverage, alert false-positive rate, strategy regret, profile repeatability, public-only versus sensor-assisted ablation']], [4 * cm, 12.8 * cm]),
      P('Defensible sentence: "Orb v1 can be tested across any available driver, circuit and supported weather regime, and it abstains when the selected conditions fall outside the evidence." Never "it works under any weather".', SM),
      P('Example of the main screen readout: current tyre medium, age 17; observed degradation 0.081 s/lap against a pre-race expectation of 0.061 (90% range 0.044 to 0.076); trend 1.33 times forecast; operational useful life 5 to 8 laps; cliff risk within 3 laps 18%; recommended pit window laps 23 to 26. Example of a change reason: "moved from lap 27 to lap 25 because the live degradation posterior rose from 0.063 to 0.081 s/lap after two clean laps and a worsening rear-traction report."', SM)]
md('## 8. Dashboard\nSeven routes; main screen is Live Tyre State; Race Twin is proof.\n')
# ---------- 9 validation ----------
S += [PageBreak(), P('9. Validation', H1),
      table([['Layer', 'What', 'Reported'],
             ['Identity and invariance', 'Actual plan gives zero delta; same-compound zero; zero degradation gives offsets plus stop effects; round trip; time accounting; one stop creates exactly one of each event', 'CI on every build'],
             ['Hidden-stop-response', 'Real stops in sealed weekends: hide post-stop laps, supply the actual intervention, predict 1, 3, 5 laps', 'MAE, cumulative, coverage, by compound, circuit, set status, flag state; versus naive and the state-space baseline'],
             ['Strategy regret', 'Pre-race plan versus hindsight oracle under a post-race reference', 'Median, mean, worst decile, within 2, 5, 10 s, probabilities'],
             ['Live-prefix evaluation', 'For every held-out race and lap k: reveal data through k, update, predict k+1, k+3, k+5, useful-life range, recommendation; continue', 'Next-lap MAE, 3- and 5-lap cumulative MAE, coverage, cliff precision and recall, Brier score, alert lead time, false alerts per stint, recommendation stability, regret, time to detect regime change'],
             ['Feedback ablation', 'Telemetry only; plus structured feedback; plus private sensors; plus both', 'Defined experiment, not a pre-written result: cliff detection lead and unnecessary-stop reduction'],
             ['Driver profile', 'Teammate-within-weekend, leave-one-circuit-out, leave-one-season-out, test-retest, minimum evidence, cold start', 'Intervals and evidence counts'],
             ['Sealed holdout and prospective', 'Whole weekends by rule, hashed before tuning; Madrid forecast hashed before the race', 'Scorecards beside hashes']], [3.2 * cm, 7.4 * cm, 6.2 * cm]),
      P('9.0 Three data splits', H2),
      table([['Split', 'Used for', 'Rules'],
             ['Development pool', 'Feature engineering, training, hyperparameters, ablations, nested leave-one-weekend-out, debugging', 'Whole weekends grouped; no lap-level random splits'],
             ['Sealed historical holdout', 'Final Ghost Strategy scorecard', 'holdout_count = clamp(round(0.18 x eligible), 4, 6), the same rule as task 0.1; whole weekends; no circuit twice; stratified on metadata only (season, circuit type, temperature regime, degradation level, compound nomination, street or permanent, SC presence, weather where data allows); sealed before further model work; results revealed only after model code, feature list, gate threshold and forecast provider are frozen; tuning after reveal is labelled post_holdout_tuning and the next prospective race becomes the new untouched test'],
             ['Prospective races', 'The strongest evidence', 'Publish forecast and hash before the race; run Live Predictor live or recorded-live; score afterwards; publish regardless of outcome']], [3 * cm, 5.4 * cm, 8.4 * cm]),
      P('9.0.1 Two scorecards, never merged', H2),
      P('Ghost Strategy scorecard: pre-race degradation MAE, interval coverage, hidden-stop next-1-lap MAE, next-3 and next-5 cumulative MAE, strategy regret, probability the recommended plan beats naive, error by circuit class, by driver support status, by actual-weather regime, abstention coverage. Driver generalisation excludes the target driver from the post-race reference and runs leave-one-driver-out where sample size permits; circuit generalisation adds leave-one-circuit-out and distinguishes a never-seen circuit from a new season of a seen circuit; counterfactual weather scenarios are never scored as accuracy.', SM),
      P('Live Predictor scorecard: next-lap error, three- and five-lap cumulative error, interval coverage, cliff-probability Brier score, alert lead time, false alerts per stint, time to detect a regime change, recommendation stability, final strategy regret, driver-feedback ablation; all from prefix evaluation where only data through lap k is revealed.', SM),
      P('9.1 Parameter policy', H2),
      P('Never "we use every available parameter". Say: Orb v1 fuses every validated signal available at deployment, records what is missing, and adjusts its confidence accordingly. Every parameter carries source, unit, sample rate, latency, availability, public or private, online-safe, missingness, quality score and ablation value; it enters production only when it improves held-out prediction, calibration or decision regret.', SM),
      P('9.2 Wording rules', H2),
      P('Race estimates are "race-derived pace-loss references"; counterfactual gains are "model-implied"; "untouched" is reserved for the sealed holdout and the prospective race; a Friday with no positive slope is "inconsistent with a wear-only interpretation"; the proxy is a "tyre demand index"; novelty reads "in the public methods we reviewed, we did not find..."; position claims only in frozen-field mode and only as distributions.', SM),
      P('9.3 Release gates', H2)] + bullets(['All v3 gates: zero delta on the actual plan, no race data in pre-race predictions, single pit loss, SC mode identified, target-driver exclusion, compound validity, weekend grouping, ordered quantiles, map equals numbers, hashes resolve, one lock, offline replay, property tests.', 'Live additions: every live value is online-safe with a timestamp; replay and batch agree; the band widens on each listed trigger in a test; every recommendation carries gain, probability, downside and change_reason; feedback can be disabled and the result reverts; sensor_mode and claim_scope rendered verbatim.', 'Rehearsal is a gate: no new feature enters the demo path after the second timed run on Sunday morning.'])
md('## 9. Validation\nIdentity; hidden-stop; regret; live-prefix; feedback ablation; profile requirements; sealed and prospective. Parameter policy; wording rules; release gates incl. live additions.\n')
# ---------- 10 narrative ----------
S += [P('10. The five-minute story', H1)] + bullets(['<b>Predict.</b> "This strategy and tyre curve were locked before the race." Forecast, pit window, hash.', '<b>Monitor.</b> Replay or ingest the race. "The medium is degrading 31% faster than expected. The driver has reported worsening rear traction. The posterior has moved outside the pre-race band." The live graph.', '<b>Decide.</b> "Orb v1 has moved the recommended stop from lap 27 to laps 24 to 25 and prefers a new medium. Median gain 3.8 seconds, 76% probability of benefit." The action list and evidence.', '<b>Prove.</b> Race Twin: "this is how the alternative propagates under the stated assumptions." Then hidden-stop-response, strategy regret, and the prospective scorecard. End on the limitation: rivals keep their observed strategy.'])
md('## 10. Story\nPredict, Monitor, Decide, Prove.\n')
# ---------- 11 risks ----------
S += [P('11. Where we might still go wrong', H1)] + bullets([
      'Two vertical slices in one sitting is a lot. The live slice is built on replay only; the moment it threatens the Race Twin slice or the Madrid anchors, it moves to Sunday morning.',
      'Public live data: OpenF1 real-time is a paid tier and its terms are non-commercial; FastF1\'s live-timing recorder is free but must run during the session. The product story rests on the method and the adapters, and says so.',
      'The engineer enters driver feedback; there is no engineer in the room on Sunday, so the demo uses recorded radio-derived entries labelled as such.',
      'A linear-Gaussian estimator with fixed regime rules is the honest Phase 0 version; the screen must not label it regime-switching until Phase 1 delivers it.',
      'The sealed holdout is task 0.1 and happens before any counterfactual or live code is tuned.',
      'The team is registered as FireBolt; the name Orb v1 goes on the product, the deck and the dashboard, and the registration name stays on the check-in sheet unless the organisers confirm a change.',
      'Rehearsal time is protected; anything unfinished at 22:30 on Saturday is cut from the demo path, not squeezed in.'])
md('## 11. Risks\nTwo slices; public live data licensing; engineer-in-loop on Sunday; honest estimator labels; holdout first; registration name; rehearsal protected.\n')
# ---------- 12 questions ----------
QA = [('What does the live system actually see during a race from public data?', 'Lap and sector times, car speed, throttle, brake, gear, DRS, gaps and positions, pit events, compound and stint information, track status, weather and team-radio records, plus our derived tyre-demand, traffic and push proxies. No tyre pressures or temperatures; those arrive only through the team adapter, and the screen says which mode it is in.'),
      ('How does driver feedback change the model without letting a driver talk the model into anything?', 'Feedback is a timestamped observation with a confidence, entered or confirmed by the engineer. It shifts the probabilities of tyre regimes, for example from normal degradation toward overheating, and the next laps of telemetry confirm or weaken it. It never adds seconds to a curve directly, and it can be disabled with the result reverting.'),
      ('Why should the confidence band ever widen during a race?', 'Because the world changes: rain, a sharp track-temperature shift, a change in push, a safety car cooling the tyres, suspected damage, a degrading feed, or behaviour outside the training support. A filter with tiny process noise becomes overconfident; ours carries explicit process noise and widening rules that are tested.'),
      ('What is the difference between the pre-race plan and the live recommendation?', 'The pre-race plan is a distribution over strategies locked and hashed before the race: primary plan, pit window, probability against the best two-stop, downside, and the condition that flips it. The live recommendation re-runs the same optimiser after every event with the posterior tyre state and shows which observation moved the call.'),
      ('How is the live model validated when nobody can see the future?', 'Prefix evaluation on held-out races: reveal data through lap k, update, predict the next one, three and five laps and the useful-life range, recommend, then step forward. We report next-lap error, cumulative error, coverage, cliff precision and recall, Brier score, alert lead time, false alerts per stint and recommendation stability.'),
      ('Why are Live Predictor and Ghost Strategy separate tools?', 'Because they answer different questions with different data boundaries. Live Predictor may only see what existed at the current timestamp and makes the call; Ghost Strategy sees the finished race and audits whether the model deserved to make it. The same frozen forecast powers both, the code enforces that neither imports the other, and the jury can see the audit without any live claim leaking into it.'),
      ('Is the driver profile a ranking of who manages tyres best?', 'No. It is a style profile from telemetry plus an outcome profile expressed as residuals after adjusting for car, circuit, compound, temperature and season, under hierarchical shrinkage, compared within weekend against the teammate. Cross-track predictions carry wide intervals and an evidence count, and unseen drivers get the population prior.'),
      ('Can I change the weather in Ghost Strategy?', 'Within supported scenarios, yes: actual historical, the pre-race snapshot, cooler, baseline and hotter dry; damp only where the model has support, wet not at all until a wet model validates. Every scenario carries a support status and the screen says "model-implied scenario, no observed outcome exists". Only actual-weather audits count as evidence.'),
      ('How do you keep the live demo from being a separate, fragile code path?', 'One event interface with three sources, replay, live and recorded-live, emitting identical events. The model and the dashboard cannot tell which is active, so the replay we rehearse is the live path we run on Sunday evening.'),
      ('What happens to the recommendation when a rival pits?', 'The optimiser re-runs, because a rival stop changes the rejoin context and the value of track position. In Phase 0 the rejoin context is the observed gap structure; Phase 1 adds live rejoin and traffic estimation; rival strategic responses are never simulated, and the screen says so.')]

S += [PageBreak(), P('13. Premium dashboard specification', H1),
      P('Premium means a serious motorsport engineering tool: restrained, dense, legible, offline. Not glass effects, not twenty colours.', SM),
      P('13.1 Technical pattern', H2)] + bullets([
      'Streamlit for the shell, controls, charts and routing: st.navigation(position="top") with a shared frame; st.fragment(run_every=...) for the live KPI strip, alerts and live charts; st.cache_data for immutable lock, Parquet and scenario outputs; st.cache_resource for thread-safe provider objects; never cache an asyncio loop or async client, use a background worker with a thread-safe queue polled by fragments.',
      'A custom bidirectional TypeScript or React Streamlit component for the animated Race Twin: browser-side time-warped map, keyboard controls, requestAnimationFrame, theme-aware; Plotly frame animation as fallback.',
      'No page imports a model; pages consume view models prepared from the lock and hashed assets.',
      'Layout: streamlit_app.py; pages/ (landing, pre_race, live_predictor, decision_board, driver_feedback, ghost_strategy, generalisation, validation); ui/ (shell, tokens, cards, charts, badges, empty_states, formatting); components/race_twin/; services/ (lock_repository, asset_repository, replay_service, event_service); state/ (app_state, query_state); theme/ (base.css, plotly_theme); tests/ (ui, screenshots, app).']) + [
      P('13.2 Visual system (frozen in ui/tokens.py and theme/base.css)', H2),
      P('Background #090C11 · surface #11161E · raised #171D27 · border #272F3B · text #F3F6FA · secondary #98A3B3 · live accent #39D0C3 · decision accent #F0B84B · critical #F16464. Compounds: soft red, medium amber, hard light grey; intermediate green and wet blue only when supported. Every colour meaning also carries an icon, label or line pattern. Inter with system fallbacks, no CDN; 8 px spacing; 12 to 16 px radius; thin borders; tabular numerals; one decimal convention; no unstyled st.metric.', MONO),
      P('Global frame, always visible: ORB V1 | LIVE PREDICTOR · Madrid 2026 · Race · Lap 24/57 · Forecast 7a92c3... · PUBLIC PROXY · IN SUPPORT · Feed latency 2.8 s.', MONO),
      P('13.3 Landing page', H2),
      P('Two large mode cards. Live Predictor: compare actual tyre behaviour against the locked pre-race forecast and receive updated pit and compound recommendations; actions Start historical replay, Load recorded-live session, Connect live feed; status strip: pre-race forecast found, live source ready, driver feedback enabled, available sets loaded. Ghost Strategy: audit a completed race, test alternative tyre strategies, inspect generalisation across supported drivers, circuits and weather; actions Historical audit, Scenario explorer, Generalisation scorecard.'),
      P('13.4 Live Predictor hero screen', H2),
      P('KPI strip, five restrained cards: LIVE DEGRADATION 0.081 s/lap, +32.8% vs forecast · USEFUL LIFE 5 to 8 laps, median 7 · CLIFF RISK 18% within 3 laps · PIT WINDOW laps 23 to 26, moved 2 laps earlier · RECOMMENDED TYRE new medium, 78% probability of gain.', MONO),
      P('2:1 layout. Left: forecast-versus-live chart with the pre-race band, corrected live observations, the live posterior, 1-, 3-, 5- and 10-lap forward prediction, the pit crossover, SC, VSC and feedback annotations, comparable historical stints as faint traces; the selected lap synchronises every chart. Right: the decision card, first recommendation with visual priority (PIT LAP 25, NEW MEDIUM; expected gain +4.1 s; probability 78%; downside q10 -1.0 s; expected rejoin 2.4 s clean-air margin; why this changed: two clean laps exceeded the forecast band, rear-traction feedback 2/5 to 4/5, track temperature +3.1 °C), then two compact alternatives (extend to lap 27; convert to two-stop). Lower rail: driver-feedback timeline, temperature and weather history, feed quality, recommendation history, the "what changed" log. No recommendation changes silently.'),
      P('13.5 Ghost Strategy hero screen', H2),
      P('Left rail: season, circuit, driver, forecast snapshot, weather context, actual strategy, intervention lap, replacement compound, set state, simulation fidelity; every scenario shows support status, seen or unseen driver and circuit, weather support, model snapshot hash. Centre: the Race Twin map with actual car, ghost car, pit-lane path, compound badges, play and pause, 1x to 10x, lap scrubber, keyboard shortcuts, time and distance delta, uncertainty halo, SC and VSC periods. Right rail: model-implied finish delta, 80% interval, probability of gain, historical-audit status, claim scope. Lower: cumulative race-time delta, lap decomposition waterfall, actual versus counterfactual tyre curves, synchronised. Banners: HISTORICAL AUDIT, OBSERVED WEATHER, HELD-OUT SCORING versus MODEL-IMPLIED SCENARIO, NO OBSERVED OUTCOME EXISTS.'),
      P('13.6 Premium acceptance criteria, added to Workstream 6', H2),
      table([['Area', 'Acceptance'], ['Cold load', 'Under 2 s from local cached artifacts'], ['Route switch', 'Under 600 ms once assets are cached'], ['Live update', 'KPI and chart fragments update without full-page flicker'], ['Race Twin', 'At least 30 FPS on the venue laptop'], ['Offline', 'No CDN, API or internet dependency for the demo'], ['Displays', 'Verified at 1440x900 and 1920x1080'], ['Layout', 'No horizontal scrolling, no clipped labels'], ['Consistency', 'Every value and unit from the lock or hashed assets'], ['Reliability', 'No browser-console errors in a full five-minute run'], ['Visual regression', 'Golden screenshots for all demo routes'], ['Accessibility', 'Keyboard operation, visible focus, non-colour status cues'], ['Failure mode', 'Every missing feed has an intentional degraded-state screen'], ['Presentation mode', 'One toggle hides engineering controls and enlarges decisive visuals'], ['Determinism', 'Recorded replay gives the same result on every run']], [3.6 * cm, 13.2 * cm]),
      P('Playwright screenshot tests: landing; Live Predictor at a stable lap; after feedback; a decision change; historical Ghost audit; Scenario Explorer; out-of-support state; missing-position fallback; offline mode.', SM)]
md('## 13. Premium dashboard\nStreamlit shell + React Race Twin component; tokens; global frame; landing; hero screens; acceptance criteria; Playwright screenshots.\n')
S += [PageBreak(), P('14. Build control: checkpoints, stops, reviewers', H1),
      P('Workstream 9, Build Control and Integration Marshal: owns progress/, checkpoints/, release/ and the integration queue; builds the heartbeat collector, checkpoint reports, last-green registry and a hidden build-control route; owns no model code, feature or scientific result; accepted when every workstream reports status, checkpoints produce a go or no-go decision, and the last-green build restores in one command. Workstream 7 remains the technical red team.'),
      P('14.1 Cadence', H2)] + bullets([
      'Every 30 minutes, heartbeat: progress/workstream_N.json with workstream, task, status GREEN AMBER RED, commit, completed, in_progress, blockers, tests_passed, tests_failed, eta_minutes, needs_review_from.',
      'Every 90 minutes, hard integration stop of 10 to 15 minutes; isolated downloads continue. Every workstream commits or records uncommitted work; Workstream 9 freezes the merge queue; Workstream 1 runs schema and fixture validation; Workstream 3 runs evaluation-boundary checks; Workstream 7 runs leakage, identity and claim checks; Workstream 6 renders affected pages and captures screenshots; the lead compares with the previous green build; tasks marked green, amber or red; one decision: GO, GO_WITH_REASSIGNMENT, ROLLBACK, CUT_FROM_DEMO. No production writes resume until GO.']) + [
      P('14.2 Checkpoint schedule', H2),
      table([['Checkpoint', 'Required state'], ['C0 Foundation', 'Naming final (Orb v1), holdout sealed, schema fixture valid, tokens committed, Workstream 9 active'], ['C1 Shared core', 'Provider A reproduces v1; both modes read the same forecast hash'], ['C2 Numerical slices', 'Ghost identity tests pass; Live cannot see future laps'], ['C3 Hero screens', 'Premium shell, Live Predictor and Ghost Strategy render'], ['C4 Integration', 'Decision engine, feedback and animation work end to end'], ['C5 Validation', 'Aggregate holdout and prefix scorecards generated'], ['C6 Release candidate', 'Offline run, screenshot tests and five-minute rehearsal pass'], ['C7 Demo freeze', 'No new feature can enter the presentation path']], [3.6 * cm, 13.2 * cm]),
      P('Each checkpoint writes checkpoints/Cn/: checkpoint.json, checkpoint.md, test_report.json, red_team_report.json, screenshots/, artifact_hashes.json, last_green.json.', SM),
      P('14.3 Stop-the-line conditions', H2),
      P('Any workstream stops the line when: the sealed holdout is opened early; a live field contains future or post-race information; forecast hashes differ between modes; provider A no longer reproduces the verified numbers; the actual-plan counterfactual is non-zero; a merge changes a headline metric without explanation; schema drift breaks another workstream; a page computes its own scientific number; dashboard and lock disagree; the app no longer works offline; a route exceeds its performance target; a workstream writes into another workstream\'s directory; a claim exceeds the selected support, fidelity or sensor mode; a red issue survives more than one checkpoint. A red issue not fixed within 20 minutes means restore last green and reassign or cut.', SM),
      P('14.4 Reviewers: no workstream accepts its own work', H2),
      table([['Deliverable', 'Builder', 'Reviewer'], ['Lock and schema', 'Workstream 1', 'Workstream 7'], ['Counterfactual core', 'Workstream 2', 'Workstreams 3 and 7'], ['Holdout evaluation', 'Workstream 3', 'Lead and Workstream 7'], ['Geometry and player', 'Workstream 4', 'Workstream 6'], ['Frozen-field model', 'Workstream 5', 'Workstreams 3 and 7'], ['Dashboard', 'Workstream 6', 'Workstreams 4, 8 and 7'], ['Live estimator', 'Workstream 8', 'Workstreams 3 and 7'], ['Build control', 'Workstream 9', 'Lead']], [5 * cm, 3 * cm, 8.8 * cm]),
      P('Review means inspecting outputs, running the acceptance test independently, comparing with the previous green artifact and signing the checkpoint report.', SM),
      P('14.5 Tasks added after 0.13', H2),
      table([['#', 'Task', 'Owner', 'Reviewer', 'Accepted when'],
             ['0.14', 'Premium dashboard system: freeze tokens, typography, spacing, chart template, status semantics, precision rules, shell and top navigation; shared cards, badges, charts, alerts, empty states, support banners; no CDN', 'Workstream 6', 'Workstream 7', 'Landing, Live Predictor and Ghost Strategy share one design system at 1440x900 and 1920x1080; screenshot tests committed'],
             ['0.15', 'Hero-mode implementation: final Live Predictor and Ghost Strategy layouts; secondary routes structurally complete, visually simpler', 'Workstream 6', 'Workstreams 4 and 8', 'Both modes independent, under two seconds, presentation path offline'],
             ['0.16', 'Build-control system: Workstream 9, 30-minute heartbeats, 90-minute stops, traffic lights, last-green rollback, checkpoint artifacts, hidden build-control route', 'Workstream 9', 'Lead', 'Two consecutive checkpoints with status from every active workstream and a successful rollback drill'],
             ['0.17', 'Visual and interaction release gate: visual regression, keyboard, console errors, offline, degraded modes, presentation mode', 'Workstream 6', 'Workstream 7', 'All golden screenshots pass; a full five-minute run shows no visual or numerical inconsistency']], [0.9 * cm, 7.2 * cm, 1.5 * cm, 1.9 * cm, 5.3 * cm]),
      P('14.6 Start conditions and waves', H2),
      P('Blocked until: the name is frozen; the holdout is sealed by the one rule; the minimal lock fixture is committed; the design tokens are committed; Workstream 9 is active and checkpoint C0 is GO. Then the workstreams start in waves: Workstreams 1, 6 and 9 first; Workstreams 2, 4 and 8 at C1; Workstreams 3, 5 and 7 as reviewers from C1 and builders from C2. Every 30 minutes must end with a demonstrably stronger green build, not eight impressive but incompatible pieces.')]
md('## 14. Build control\nWorkstream 9; heartbeats; 90-min stops; checkpoints C0-C7; stop-the-line; reviewers; tasks 0.14-0.17; start conditions and waves.\n')

S += [PageBreak(), P('15. Ten questions this system must survive', H1)]
for i, (q, a) in enumerate(QA, 1): S += [KeepTogether([P(f'<b>{i}. {q}</b>', B), P(a)])]
md('## 12. Ten questions\n' + '\n'.join(f'**{i}. {q}**\n\n{a}\n' for i, (q, a) in enumerate(QA, 1)))
doc = SimpleDocTemplate('out/Orb_v1_Roadmap_v5.pdf', pagesize=A4, leftMargin=1.8 * cm, rightMargin=1.8 * cm, topMargin=1.6 * cm, bottomMargin=1.6 * cm, title='Orb v1 Live Tyre Intelligence roadmap v4', author='Team Orb v1')
def footer(c, d): c.saveState(); c.setFont('Helvetica', 7.5); c.setFillColor(colors.HexColor('#6B7280')); c.drawString(1.8 * cm, 1 * cm, 'Orb v1 Live Tyre Intelligence · roadmap v5 · build contract'); c.drawRightString(A4[0] - 1.8 * cm, 1 * cm, str(d.page)); c.restoreState()
doc.build(S, onFirstPage=footer, onLaterPages=footer); open('out/ROADMAP_v5.md', 'w').write('\n'.join(MD)); print('roadmap v5 built')
