"""Roadmap v4: Orb v1 Live Tyre Intelligence -> out/Orb_v1_Roadmap_v4.pdf and out/ROADMAP_v4.md"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
ss = getSampleStyleSheet()
H1 = ParagraphStyle('H1', parent=ss['Heading1'], fontSize=16.5, leading=20, spaceBefore=8, spaceAfter=7)
H2 = ParagraphStyle('H2', parent=ss['Heading2'], fontSize=12, spaceBefore=8, spaceAfter=4)
B = ParagraphStyle('B', parent=ss['BodyText'], fontSize=9.8, leading=13.6, spaceAfter=5)
SM = ParagraphStyle('SM', parent=B, fontSize=8.4, leading=11, textColor=colors.HexColor('#4B5563'))
BUL = ParagraphStyle('BUL', parent=B, leftIndent=12, bulletIndent=2, spaceAfter=2.5)
MONO = ParagraphStyle('MONO', parent=B, fontName='Courier', fontSize=8, leading=10.2, leftIndent=8, spaceAfter=4)
CELL = ParagraphStyle('CELL', parent=B, fontSize=8.1, leading=10.3, spaceAfter=0); CELLB = ParagraphStyle('CELLB', parent=CELL, fontName='Helvetica-Bold')
def P(t, s=B): return Paragraph(t, s)
def bullets(items): return [Paragraph(t, BUL, bulletText='•') for t in items]
def table(rows, widths):
    data = [[Paragraph(str(c), CELLB if i == 0 else CELL) for c in r] for i, r in enumerate(rows)]
    t = Table(data, colWidths=widths, repeatRows=1); t.setStyle(TableStyle([('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#C7CCD4')), ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E5E7EB')), ('VALIGN', (0, 0), (-1, -1), 'TOP'), ('LEFTPADDING', (0, 0), (-1, -1), 4), ('RIGHTPADDING', (0, 0), (-1, -1), 4), ('TOPPADDING', (0, 0), (-1, -1), 3), ('BOTTOMPADDING', (0, 0), (-1, -1), 3)])); return t
MD = []
def md(t): MD.append(t)
S = [Spacer(1, 1.2 * cm), P('Orb v1 Live Tyre Intelligence: roadmap v4', ParagraphStyle('T', parent=ss['Title'], fontSize=25, leading=30, alignment=0)),
     P('Predict. Monitor. Decide. Prove.', ParagraphStyle('TG', parent=B, fontSize=14, leading=18, textColor=colors.HexColor('#111827'))),
     P('A pre-race and real-time tyre-performance intelligence system with driver feedback, sensor-ready live estimation, risk-aware pit recommendations and Race Twin validation.', ParagraphStyle('ST', parent=B, fontSize=11.5, leading=16, textColor=colors.HexColor('#374151'))),
     Spacer(1, 6), P('Team Orb v1 (registered with the organisers as FireBolt) &middot; TrackShift 2026 &middot; drafted 12 September, 14:05 IST, for critique before any workstream starts.', SM), Spacer(1, 10)]
md('# Orb v1 Live Tyre Intelligence: roadmap v4\n\n*Predict. Monitor. Decide. Prove.* Drafted 12 Sep 14:05 IST for critique.\n')
# ---------- 0 ----------
S += [P('0. What Orb v1 is', H1),
      P('Orb v1 is a pre-race and live tyre-intelligence system. Before the race, it estimates compound-specific degradation distributions and recommends strategy and pit windows from practice, historical, weather and circuit data. During the race, it fuses corrected pace, live telemetry, track conditions, traffic, structured driver feedback and private tyre sensors when available to update a probabilistic tyre-performance state every lap. It forecasts remaining operational tyre life and cliff risk, then ranks pit and compound actions by expected race-time benefit and downside. Race Twin is the proof-and-explanation layer: it replays alternative tyre choices, exposes how each prediction affects the race and connects the model to its held-out validation. Public-data mode operates with wider uncertainty; team-data mode replaces assumptions with direct measurements and tightens the same model.'),
      P('The verified core is untouched: one lock as the source of truth, the stint fixed-effects estimator, exact strategy enumeration, compound offsets, pit-loss handling, the post-race replay, and the 11-weekend, 29-case evidence base (0.023 against 0.137 s/lap, 28 of 29). Everything below is layered on top through interfaces, so a component can fail without taking the product with it.', SM),
      P('0.1 Six capabilities, feasibility verdicts', H2),
      table([['Capability', 'Verdict', 'Correct implementation', 'Reality check'],
             ['Driver in the loop', 'Yes, core feature', 'Timestamped, structured observation with uncertainty that shifts regime probabilities; never a direct seconds adjustment; the engineer enters or confirms it, the driver never touches a screen', 'Calibration profiles per driver need history; today the form, log, audit and regime update are built, calibration is Phase 2'],
             ['Live tyre telemetry', 'Yes, in team mode', 'Public mode ingests timing, car data, gaps, weather, radio records and derived proxies; team mode adds pressures, temperatures, slip, steering, fuel, set identity through the same adapter interface', 'The 2026 regulations mandate tyre pressure and temperature sensors on every car, but those channels are not public. Public live data: FastF1\'s live-timing recorder is free and must run during the session; OpenF1 real-time is a paid tier, its history is free with a delay'],
             ['Historical versus live trend', 'Yes, the main screen', 'Pre-race prior band, live corrected observations, live posterior curve, comparable historical stints, 1-3-5-10-lap forward prediction, cliff probability, crossover', 'Demonstrated as replay today; genuinely live for the Madrid race on Sunday evening, after the event, through the recorded-live source'],
             ['Pre-race tyre strategy', 'Already present', 'Expand from one best plan to probability-ranked pit windows and alternatives with expected gain, downside and the condition that flips the call', 'One to two hours; the enumeration exists'],
             ['Live pit and tyre recommendation', 'Yes, the main decision output', 'Re-run the optimiser after every relevant event; ranked actions with gain, probability, downside, rejoin context, evidence, and which observation changed the call', 'Rejoin and traffic estimation is Phase 1; in Phase 0 the rejoin context is the observed gap structure'],
             ['Driver degradation profile', 'Yes, but hardest', 'Style profile from telemetry plus outcome profile as conditional residuals under hierarchical shrinkage with teammate-within-weekend comparisons; cross-track prediction with wide intervals', 'Phase 2: needs three seasons and leave-one-circuit-out and leave-one-season-out validation; never a raw ranking']], [2.6 * cm, 2.1 * cm, 6.3 * cm, 5.8 * cm])]
md('## 0. Orb v1\nPre-race prior -> live posterior every lap (telemetry, conditions, traffic, driver feedback, private sensors when available) -> useful life and cliff risk -> ranked pit/compound actions -> Race Twin proof. Six capabilities: all feasible; live telemetry in team mode; driver profile hardest (Phase 2).\n')
# ---------- 1 architecture ----------
S += [P('1. Architecture and components', H1),
      P('Practice and historical data -> pre-race tyre and strategy prior -> live timing, telemetry, weather, traffic + structured driver feedback + private tyre sensors when available -> probabilistic live tyre-state estimator -> live degradation curve and remaining-useful-life forecast -> exact strategy and pit-window optimiser -> ranked action list with expected gain, uncertainty and reasons -> Race Twin and post-race scorecard.', MONO),
      P('Four separate components, never one model: <b>PreRaceCurveProvider</b>, <b>LiveTyreStateEstimator</b>, <b>StrategyOptimizer</b>, <b>RaceTwinEngine</b>; plus <b>TelemetryAdapter</b>, <b>DriverFeedbackAdapter</b>, <b>DriverProfileProvider</b>, and <b>RaceEventSource</b> (replay, live, recorded-live) so that live mode is never a separate, barely tested code path.'),
      P('Live model of record: a robust regime-switching Bayesian state-space model (latent thermal state, performance-wear state, grip loss, degradation rate, cliff hazard, anomaly probability; regimes WARMUP, NORMAL, OVERHEATING, GRAINING, RECOVERING, ACCELERATING_WEAR, CLIFF, ANOMALY) with explicit process noise so the band can widen, a boosted residual model for systematic error, and the exact optimiser. The liquid network is at most an optional high-frequency thermal encoder, kept only if it beats hand features and an exponentially weighted proxy on held-out races. The buildable Phase 0 version of the estimator is linear-Gaussian with fixed regime rules; the full regime switching is Phase 1.', SM)]
md('## 1. Architecture\nPreRaceCurveProvider, LiveTyreStateEstimator, StrategyOptimizer, RaceTwinEngine + adapters + RaceEventSource. Live model: regime-switching Bayesian state-space with process noise, boosted residual, exact optimiser; LNN optional encoder only.\n')
# ---------- 2 sittings ----------
S += [P('2. Sittings and anchors', H1),
      table([['Sitting', 'When (IST)', 'Scope', 'Anchors'],
             ['1 (now)', 'Sat 14:15 to 23:30', 'Phase 0: Race Twin vertical slice plus the live vertical slice on replay, sealed holdout, contracts, provider abstraction; parallel non-blocking model and feature work', 'Madrid FP3 refresh 17:30; qualifying refresh and hashed forecast 20:45; timed rehearsal 22:30'],
             ['2', 'Sun 05:30 to the slot, then evening', 'Phase 1 subset before the slot: all drivers of one race, live-prefix evaluation aggregate, decision board, driver-feedback demo, two rehearsals; rest after the slot', 'Smoke test 08:00; presentation; Madrid race 18:30 live through the recorded-live source; scorecard'],
             ['3', 'After the event', 'Phase 2: profiles, regime model, absolute compounds, sensor adapters, documents', 'Publish the scorecard beside the pre-race hash']], [1.7 * cm, 3 * cm, 7.4 * cm, 4.7 * cm]),
      P('Three-season download: about 253 of 350 sessions on disk at 13:35, five workers still running, automatic cleanup pass queued; complete by about 15:15. Heavy workstreams are limited to four concurrent processes until then.', SM)]
md('## 2. Sittings\n1: Sat 14:15-23:30 Phase 0 with Madrid anchors. 2: Sun pre-slot subset of Phase 1, rest after. 3: post-event Phase 2.\n')
# ---------- 3 phase 0 ----------
S += [PageBreak(), P('3. Phase 0, this sitting: two vertical slices', H1),
      P('Complete when both slices work end to end on one race and one driver: (a) Race Twin: select, choose lap and compound, compute the alternative race, cumulative delta with uncertainty, two blips, identity test passed; (b) Live: load the pre-race forecast, replay the race one lap at a time, update the posterior, accept structured driver feedback, update the pit recommendation, then open Race Twin. RaceEventSource and recursive updating are promoted into this phase.'),
      P('3.1 Mandatory, Race Twin slice', H2),
      table([['#', 'Task', 'Owner', 'Accepted when'],
             ['0.1', 'Seal the holdout before anything is tuned: deterministic rule over metadata and feed quality (seed 2026, two races per season 2023 to 2025, stratified by circuit class, compound nomination, temperature, stop count, SC presence, one street circuit); manifest and sha256 committed; builders never see per-race results', 'Workstream 3', 'prohibited_for_tuning true; selection reproducible'],
             ['0.2', 'Minimal lock v2: pydantic models, JSON schema, additionalProperties false in stable blocks, extensions namespace, v1 adapter, golden fixtures, atomic writes, sidecars by hash; new blocks input_availability, pre_race_forecast, live_tyre_state, driver_feedback_events, live_recommendations, driver_profile, counterfactuals, validation', 'Workstream 1', 'Downstream workstreams work from the fixture; schema test on merge; no large arrays in the lock'],
             ['0.3', 'PreRaceCurveProvider with the current estimator as provider A', 'Workstream 2', 'Reproduces the v1 curves exactly'],
             ['0.4', 'Counterfactual core, fixed-context and tyre-only: decomposition Y = B + T + P + I + e; standardised pit event as a distribution; SC and VSC as fixed observed schedule with SC pit loss and frozen pace gains; contaminated laps reconstructed', 'Workstream 2', 'Identity, same-compound, no-degradation, round-trip and time-accounting tests pass; scenario under 250 ms'],
             ['0.5', 'Track geometry and time-warped two-blip player with Plotly fallback; uncertainty by whole-curve sampling with precomputed quantiles', 'Workstream 4', 'Actual-plan ghost overlays the driver; frame rate offline; quantiles ordered'],
             ['0.6', 'Race Twin route in the existing dashboard: controls, map, evidence strip, lap waterfall, race-time chart, assumptions box, fidelity switch', 'Workstream 6', 'Under two seconds; offline']], [0.9 * cm, 8.9 * cm, 1.6 * cm, 5.4 * cm]),
      P('3.2 Mandatory, live slice', H2),
      table([['#', 'Task', 'Owner', 'Accepted when'],
             ['0.7', 'Live-state contract: live_tyre_state and live_recommendation schemas; every value timestamped and online-safe', 'Workstream 1', 'Schema test passes; no field can carry future data'],
             ['0.8', 'Replay state estimator: lap-by-lap posterior update from the pre-race prior (linear-Gaussian, explicit process noise, resets at stops, widening rules for rain, temperature shifts, push changes, SC cooling, feed degradation, out-of-support)', 'Workstream 8', 'No future data; batch and replay results agree; band widens on the listed triggers'],
             ['0.9', 'RaceEventSource: replay and recorded-live sources emitting position_update, lap_completed, pit_entry, pit_exit, weather_update, track_status, overtake, retirement, feed_quality_warning', 'Workstream 2', 'Model and dashboard cannot tell which source is active'],
             ['0.10', 'Driver-feedback input: structured engineer form and event log (timestamp, lap, axle, corner phase, symptom, severity, trend, confidence, source, raw message, engineer confirmation); feedback shifts regime probabilities, never adds seconds directly; can be enabled, disabled, audited', 'Workstream 8', 'Feedback effect visible on the posterior and reversible'],
             ['0.11', 'Live comparison graph: prior band, corrected observations, posterior curve, comparable historical stints, 1-3-5-10-lap forward prediction, cliff probability, crossover', 'Workstream 6', 'Updates per event without retraining or page reload'],
             ['0.12', 'Action engine: optimiser re-run per event; ranked actions with expected gain, probability, downside, target compound and set, rejoin context, evidence, and change_reason naming the observation that moved the call', 'Workstream 8', 'Every recommendation carries gain, risk and explanation; recommendation history logged'],
             ['0.13', 'Red team on both slices; anchors: Madrid FP3 refresh, qualifying refresh, hashed forecast, deck slide, timed run', 'Workstream 7, Lead', 'blocking_issues.json empty; hash before 21:45']], [0.9 * cm, 8.9 * cm, 1.6 * cm, 5.4 * cm]),
      P('3.3 Parallel, non-blocking', H2)] + bullets(['Weather-only feature pass: per-lap track and air temperature, deltas, humidity, wind, rainfall, thermal proxy, load-dose split, run phases, used-set flag, "tyre demand index".', 'Errors-in-variables Friday-to-Sunday regression on three seasons, chronological evaluation, weekend bootstrap, risk-coverage, information gate; provider B only if it wins held out.', 'Downloads and cleanup.']) + [
      P('3.4 Not tonight', H2)] + bullets(['Rebuilding existing views for aesthetics; driver profiles; TUMFTM; multi-agent simulation; any attempt to make the liquid network win.'])
md('## 3. Phase 0\nRace Twin slice (0.1-0.6) + live slice (0.7-0.13): live-state contract, replay estimator with widening, RaceEventSource, driver-feedback input, live comparison graph, action engine, red team, Madrid anchors.\n')
# ---------- 4 phase 1 ----------
S += [Spacer(1, 6), P('4. Phase 1, second sitting: operational live intelligence and validation', H1)] + bullets([
      'Live adapters: FastF1 live-timing recorder as the free public source, OpenF1 adapter where licensed, recorded-live fallback, team sensor adapter interface with clock synchronisation.',
      'Driver-feedback radio and manual adapter; available tyre-set inventory; live rejoin and traffic estimation; alert and recommendation history; prefix-based live validation.',
      'Race Twin at scale: all drivers of one race, then the sealed holdout, then every 2026 race; hidden-stop-response evaluation; strategy regret under a post-race reference; leave-one-driver-out audit; frozen-field simulator behind the fixed-context fallback with SC-neutral and SC-aware outputs.',
      'Dashboard: fidelity switch live, rival blips, position distributions, validation views, historical replay controls, the prospective Madrid case live through the recorded-live source on Sunday evening.',
      'Documents regenerated from lock v2; demo path rehearsed twice before the slot.'])
md('## 4. Phase 1\nLive adapters, feedback adapter, inventory, rejoin, histories, prefix validation; Race Twin scale and validation; frozen field behind fallback; dashboard integration; documents.\n')
# ---------- 5 phase 2 ----------
S += [P('5. Phase 2, third sitting: advanced generalisation', H1)] + bullets([
      'Driver style and outcome profiles with hierarchical shrinkage; cross-track prediction; driver-feedback calibration; teammate-within-weekend, leave-one-circuit-out, leave-one-season-out, test-retest, minimum evidence, cold start.',
      'Regime-switching state-space live estimator; boosted residual benchmark with weekend-grouped validation; cross-season and regulation-domain adaptation.',
      'Absolute C1 to C5 compound mapping; corner-specific thermal and load modelling; per-corner team-sensor mode; private-data sensor-fusion evaluation.',
      'Shape-constrained wear curve; better pit-loss and warm-up model; corner-weighted spatial delta; traffic interaction; TUMFTM comparison; multi-agent simulation last; liquid network only as an optional encoder.'])
md('## 5. Phase 2\nDriver profiles; regime-switching estimator; boosted residual; absolute compounds; sensor modes; shape-constrained wear; TUMFTM; multi-agent last.\n')
# ---------- 6 workstreams ----------
S += [P('6. Workstreams, ownership, integration', H1),
      table([['Workstream', 'Owns', 'Builds', 'Accepted when'],
             ['1 Contract and fixtures', 'schemas/, fixtures/, validators/', 'lock v2 incl. live blocks, fixtures, validator, v1 adapter', 'Downstream workstreams work from fixtures; no large arrays in the lock'],
             ['2 Counterfactual core and events', 'counterfactual/, events/', 'Decomposition, interventions, pit and SC rules, Monte Carlo, provider interface, RaceEventSource', 'Identity tests pass; scenario under 250 ms; sources interchangeable'],
             ['3 Blind evaluation', 'evaluation/', 'Sealed holdout, hidden-stop-response, regret, live-prefix evaluation, calibration, weekend bootstrap, scorecards', 'Builders cannot see per-race results; every metric weekend-grouped'],
             ['4 Geometry and animation', 'replay/, dashboard/components/', 'Canonical path, pit lane, time warping, browser player, fallbacks', 'Ghost overlays the driver; frame rate offline'],
             ['5 Frozen field', 'interaction/', 'Rival trajectories, following loss, overtake probability, position distribution', 'Observed plan reconstructs observed ordering; fallback exact'],
             ['6 Dashboard', 'app routes, views/', 'Pre-race plan, live tyre state (main), decision board, driver feedback, driver profile, Race Twin, validation', 'No training in the dashboard; every number from lock or hashed asset; under two seconds; offline'],
             ['7 Red team', 'none', 'red_team_report.json, blocking_issues.json, claim_evidence_map.json', 'No release with a blocking issue'],
             ['8 Live intelligence', 'live/, decision/', 'LiveTyreStateEstimator, DriverFeedbackAdapter, StrategyOptimizer re-run logic, action engine, recommendation history', 'No future data in replay; band widens on triggers; every action explained']], [2.6 * cm, 2.9 * cm, 6 * cm, 5.3 * cm]),
      P('Integration rules: directory ownership; validator, identity tests and release gates on every merge; numbers reach slides only through the lock; at most four heavy processes until the download finishes; a claim on a screen may not exceed the selected fidelity or sensor mode; the claim_scope and sensor_mode fields are rendered, not paraphrased.', SM)]
md('## 6. Workstreams\nEight workstreams by directory; gates on merge; claims bound to mode.\n')
# ---------- 7 contracts ----------
S += [PageBreak(), P('7. Contracts', H1),
      P('PreRaceCurveProvider.predict_curve(event, driver, compound, context, age_range) -> CurveDistribution(mean, q10, q50, q90, cliff_probability, provenance)', MONO),
      P('LiveTyreStateEstimator.update(prior_state, telemetry, context, driver_feedback=None, sensor_data=None) -> TyreStateDistribution', MONO),
      P('StrategyOptimizer.recommend(tyre_state, available_sets, race_context, competitor_context) -> RankedActions', MONO),
      P('DriverFeedbackAdapter.parse(feedback_event) -> FeedbackObservation;  DriverProfileProvider.predict(driver, circuit, compound, car_context, weather) -> DriverTyrePrior', MONO),
      P('RaceEventSource.events() -> RaceEvent; implementations Replay, Live, RecordedLive', MONO),
      P('7.1 live_tyre_state fields', H2),
      P('lap, timestamp, compound, tyre_age, state_regime, corrected_pace_loss, degradation_rate, thermal_stress_index, performance_wear_index, useful_laps_q10, useful_laps_q50, useful_laps_q90, cliff_probability_3_laps, cliff_probability_5_laps, trend_vs_pre_race, confidence, sensor_mode (PUBLIC PROXY or TEAM SENSOR), support_status, sensor_availability, source_latency, missing_channels, quality_status', MONO),
      P('7.2 live_recommendation fields', H2),
      P('action, pit_window, target_compound, target_set, expected_gain_median, expected_gain_q10, expected_gain_q90, probability_of_gain, rejoin_context, reasons, constraints, changed_since_last_update, change_reason', MONO),
      P('7.3 driver feedback event', H2),
      P('timestamp, lap, axle (front, rear, all, unknown), corner_phase (braking, entry, mid, exit, traction), symptom (understeer, oversteer, sliding, graining, overheating, vibration, lack_of_grip), severity 1 to 5, trend, driver_confidence, source, raw_message, engineer_confirmed', MONO),
      P('Public mode never displays physical tread remaining, physical wear percentages or per-tyre structural health. It displays performance_loss, operational_useful_laps_remaining, thermal_stress_index and performance_wear_index. Every output carries sensor_availability, source_latency, missing_channels, quality_status and confidence_effect.', SM)]
md('## 7. Contracts\nFive interfaces; live_tyre_state, live_recommendation and driver feedback fields; public-mode display rules.\n')
# ---------- 8 dashboard ----------
S += [P('8. Dashboard structure', H1),
      table([['Route', 'Content'],
             ['1 Pre-race plan', 'Compound curves and bands, strategy tree, pit windows, one-stop versus two-stop probability, weather scenarios, driver-specific prior, tyre inventory'],
             ['2 Live tyre state (main screen)', 'Current compound and age; forecast versus live graph; degradation rate; trend versus expected; thermal and wear indices; useful laps remaining; cliff probability; data-quality and sensor-mode status'],
             ['3 Decision board', 'Top three actions with target compound and set, pit window, expected gain, downside, rejoin traffic, and why the recommendation changed'],
             ['4 Driver feedback', 'Structured entry, latest feedback, whether telemetry supports it, effect on posterior and recommendation, calibration history'],
             ['5 Driver profile', 'Style dimensions, context-adjusted degradation, track-class and compound behaviour, teammate comparison, confidence and evidence count (Phase 2)'],
             ['6 Race Twin', 'Ghost map, counterfactual waterfall, strategy replay, model-implied gain, hidden-stop-response results, prospective scorecard'],
             ['7 Validation', 'Pre-race held-out accuracy, live next-lap and multi-lap accuracy, interval coverage, alert false-positive rate, strategy regret, profile repeatability, public-only versus sensor-assisted ablation']], [4 * cm, 12.8 * cm]),
      P('Example of the main screen readout: current tyre medium, age 17; observed degradation 0.081 s/lap against a pre-race expectation of 0.061 (90% range 0.044 to 0.076); trend 1.33 times forecast; operational useful life 5 to 8 laps; cliff risk within 3 laps 18%; recommended pit window laps 23 to 26. Example of a change reason: "moved from lap 27 to lap 25 because the live degradation posterior rose from 0.063 to 0.081 s/lap after two clean laps and a worsening rear-traction report."', SM)]
md('## 8. Dashboard\nSeven routes; main screen is Live Tyre State; Race Twin is proof.\n')
# ---------- 9 validation ----------
S += [PageBreak(), P('9. Validation', H1),
      table([['Layer', 'What', 'Reported'],
             ['Identity and invariance', 'Actual plan gives zero delta; same-compound zero; zero degradation gives offsets plus stop effects; round trip; time accounting; one stop creates exactly one of each event', 'CI on every build'],
             ['Hidden-stop-response', 'Real stops in sealed weekends: hide post-stop laps, supply the actual intervention, predict 1, 3, 5 laps', 'MAE, cumulative, coverage, by compound, circuit, set status, flag state; versus naive and the state-space baseline'],
             ['Strategy regret', 'Pre-race plan versus hindsight oracle under a post-race reference', 'Median, mean, worst decile, within 2, 5, 10 s, probabilities'],
             ['Live-prefix evaluation', 'For every held-out race and lap k: reveal data through k, update, predict k+1, k+3, k+5, useful-life range, recommendation; continue', 'Next-lap MAE, 3- and 5-lap cumulative MAE, coverage, cliff precision and recall, Brier score, alert lead time, false alerts per stint, recommendation stability, regret, time to detect regime change'],
             ['Feedback ablation', 'Telemetry only; plus structured feedback; plus private sensors; plus both', 'Defined experiment, not a pre-written result: cliff detection lead and unnecessary-stop reduction'],
             ['Driver profile', 'Teammate-within-weekend, leave-one-circuit-out, leave-one-season-out, test-retest, minimum evidence, cold start', 'Intervals and evidence counts'],
             ['Sealed holdout and prospective', 'Whole weekends by rule, hashed before tuning; Madrid forecast hashed before the race', 'Scorecards beside hashes']], [3.2 * cm, 7.4 * cm, 6.2 * cm]),
      P('9.1 Parameter policy', H2),
      P('Never "we use every available parameter". Say: Orb v1 fuses every validated signal available at deployment, records what is missing, and adjusts its confidence accordingly. Every parameter carries source, unit, sample rate, latency, availability, public or private, online-safe, missingness, quality score and ablation value; it enters production only when it improves held-out prediction, calibration or decision regret.', SM),
      P('9.2 Wording rules', H2),
      P('Race estimates are "race-derived pace-loss references"; counterfactual gains are "model-implied"; "untouched" is reserved for the sealed holdout and the prospective race; a Friday with no positive slope is "inconsistent with a wear-only interpretation"; the proxy is a "tyre demand index"; novelty reads "in the public methods we reviewed, we did not find..."; position claims only in frozen-field mode and only as distributions.', SM),
      P('9.3 Release gates', H2)] + bullets(['All v3 gates: zero delta on the actual plan, no race data in pre-race predictions, single pit loss, SC mode identified, target-driver exclusion, compound validity, weekend grouping, ordered quantiles, map equals numbers, hashes resolve, one lock, offline replay, property tests.', 'Live additions: every live value is online-safe with a timestamp; replay and batch agree; the band widens on each listed trigger in a test; every recommendation carries gain, probability, downside and change_reason; feedback can be disabled and the result reverts; sensor_mode and claim_scope rendered verbatim.', 'Rehearsal is a gate: no new feature enters the demo path after the second timed run on Sunday morning.'])
md('## 9. Validation\nIdentity; hidden-stop; regret; live-prefix; feedback ablation; profile requirements; sealed and prospective. Parameter policy; wording rules; release gates incl. live additions.\n')
# ---------- 10 narrative ----------
S += [P('10. The five-minute story', H1)] + bullets(['<b>Predict.</b> "This strategy and tyre curve were locked before the race." Forecast, pit window, hash.', '<b>Monitor.</b> Replay or ingest the race. "The medium is degrading 31% faster than expected. The driver has reported worsening rear traction. The posterior has moved outside the pre-race band." The live graph.', '<b>Decide.</b> "Orb v1 has moved the recommended stop from lap 27 to laps 24 to 25 and prefers a new medium. Median gain 3.8 seconds, 76% probability of benefit." The action list and evidence.', '<b>Prove.</b> Race Twin: "this is how the alternative propagates under the stated assumptions." Then hidden-stop-response, strategy regret, and the prospective scorecard. End on the limitation: rivals keep their observed strategy.'])
md('## 10. Story\nPredict, Monitor, Decide, Prove.\n')
# ---------- 11 risks ----------
S += [P('11. Where we might still go wrong', H1)] + bullets([
      'Two vertical slices in one sitting is a lot. The live slice is built on replay only; the moment it threatens the Race Twin slice or the Madrid anchors, it moves to Sunday morning.',
      'Public live data: OpenF1 real-time is a paid tier and its terms are non-commercial; FastF1\'s live-timing recorder is free but must run during the session. The product story rests on the method and the adapters, and says so.',
      'The engineer enters driver feedback; there is no engineer in the room on Sunday, so the demo uses recorded radio-derived entries labelled as such.',
      'A linear-Gaussian estimator with fixed regime rules is the honest Phase 0 version; the screen must not label it regime-switching until Phase 1 delivers it.',
      'The sealed holdout is task 0.1 and happens before any counterfactual or live code is tuned.',
      'The team is registered as FireBolt; the name Orb v1 goes on the product, the deck and the dashboard, and the registration name stays on the check-in sheet unless the organisers confirm a change.',
      'Rehearsal time is protected; anything unfinished at 22:30 on Saturday is cut from the demo path, not squeezed in.'])
md('## 11. Risks\nTwo slices; public live data licensing; engineer-in-loop on Sunday; honest estimator labels; holdout first; registration name; rehearsal protected.\n')
# ---------- 12 questions ----------
QA = [('What does the live system actually see during a race from public data?', 'Lap and sector times, car speed, throttle, brake, gear, DRS, gaps and positions, pit events, compound and stint information, track status, weather and team-radio records, plus our derived tyre-demand, traffic and push proxies. No tyre pressures or temperatures; those arrive only through the team adapter, and the screen says which mode it is in.'),
      ('How does driver feedback change the model without letting a driver talk the model into anything?', 'Feedback is a timestamped observation with a confidence, entered or confirmed by the engineer. It shifts the probabilities of tyre regimes, for example from normal degradation toward overheating, and the next laps of telemetry confirm or weaken it. It never adds seconds to a curve directly, and it can be disabled with the result reverting.'),
      ('Why should the confidence band ever widen during a race?', 'Because the world changes: rain, a sharp track-temperature shift, a change in push, a safety car cooling the tyres, suspected damage, a degrading feed, or behaviour outside the training support. A filter with tiny process noise becomes overconfident; ours carries explicit process noise and widening rules that are tested.'),
      ('What is the difference between the pre-race plan and the live recommendation?', 'The pre-race plan is a distribution over strategies locked and hashed before the race: primary plan, pit window, probability against the best two-stop, downside, and the condition that flips it. The live recommendation re-runs the same optimiser after every event with the posterior tyre state and shows which observation moved the call.'),
      ('How is the live model validated when nobody can see the future?', 'Prefix evaluation on held-out races: reveal data through lap k, update, predict the next one, three and five laps and the useful-life range, recommend, then step forward. We report next-lap error, cumulative error, coverage, cliff precision and recall, Brier score, alert lead time, false alerts per stint and recommendation stability.'),
      ('Will you show tread remaining?', 'Not in public mode. Tread depth is not observable in public data and any such number would be a formula wearing a unit. We show performance loss, operational useful laps, a thermal stress index and a performance wear index, and the team adapter is where physical measurements would enter.'),
      ('Is the driver profile a ranking of who manages tyres best?', 'No. It is a style profile from telemetry plus an outcome profile expressed as residuals after adjusting for car, circuit, compound, temperature and season, under hierarchical shrinkage, compared within weekend against the teammate. Cross-track predictions carry wide intervals and an evidence count, and unseen drivers get the population prior.'),
      ('What did the liquid network contribute?', 'An honest ablation: with the same inputs, a linear model matched it on held-out stints, and the inputs delivered the gain. It remains an optional high-frequency thermal encoder, kept only if it beats hand features and a simple exponentially weighted proxy on held-out races.'),
      ('How do you keep the live demo from being a separate, fragile code path?', 'One event interface with three sources, replay, live and recorded-live, emitting identical events. The model and the dashboard cannot tell which is active, so the replay we rehearse is the live path we run on Sunday evening.'),
      ('What happens to the recommendation when a rival pits?', 'The optimiser re-runs, because a rival stop changes the rejoin context and the value of track position. In Phase 0 the rejoin context is the observed gap structure; Phase 1 adds live rejoin and traffic estimation; rival strategic responses are never simulated, and the screen says so.')]
S += [PageBreak(), P('12. Ten questions this system must survive', H1)]
for i, (q, a) in enumerate(QA, 1): S += [KeepTogether([P(f'<b>{i}. {q}</b>', B), P(a)])]
md('## 12. Ten questions\n' + '\n'.join(f'**{i}. {q}**\n\n{a}\n' for i, (q, a) in enumerate(QA, 1)))
doc = SimpleDocTemplate('out/Orb_v1_Roadmap_v4.pdf', pagesize=A4, leftMargin=1.8 * cm, rightMargin=1.8 * cm, topMargin=1.6 * cm, bottomMargin=1.6 * cm, title='Orb v1 Live Tyre Intelligence roadmap v4', author='Team Orb v1')
def footer(c, d): c.saveState(); c.setFont('Helvetica', 7.5); c.setFillColor(colors.HexColor('#6B7280')); c.drawString(1.8 * cm, 1 * cm, 'Orb v1 Live Tyre Intelligence · roadmap v4 · draft for critique'); c.drawRightString(A4[0] - 1.8 * cm, 1 * cm, str(d.page)); c.restoreState()
doc.build(S, onFirstPage=footer, onLaterPages=footer); open('out/ROADMAP_v4.md', 'w').write('\n'.join(MD)); print('roadmap v4 built')
