"""Roadmap v3: Orb v1 Race Twin programme -> out/Orb_v1_Roadmap_v3.pdf and out/ROADMAP_v3.md"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
ss = getSampleStyleSheet()
H1 = ParagraphStyle('H1', parent=ss['Heading1'], fontSize=16.5, leading=20, spaceBefore=8, spaceAfter=7)
H2 = ParagraphStyle('H2', parent=ss['Heading2'], fontSize=12, spaceBefore=8, spaceAfter=4)
B = ParagraphStyle('B', parent=ss['BodyText'], fontSize=9.8, leading=13.6, spaceAfter=5)
SM = ParagraphStyle('SM', parent=B, fontSize=8.4, leading=11, textColor=colors.HexColor('#4B5563'))
BUL = ParagraphStyle('BUL', parent=B, leftIndent=12, bulletIndent=2, spaceAfter=2.5)
MONO = ParagraphStyle('MONO', parent=B, fontName='Courier', fontSize=8.2, leading=10.5, leftIndent=8, spaceAfter=4)
CELL = ParagraphStyle('CELL', parent=B, fontSize=8.1, leading=10.3, spaceAfter=0); CELLB = ParagraphStyle('CELLB', parent=CELL, fontName='Helvetica-Bold')
def P(t, s=B): return Paragraph(t, s)
def bullets(items): return [Paragraph(t, BUL, bulletText='•') for t in items]
def table(rows, widths):
    data = [[Paragraph(str(c), CELLB if i == 0 else CELL) for c in r] for i, r in enumerate(rows)]
    t = Table(data, colWidths=widths, repeatRows=1); t.setStyle(TableStyle([('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#C7CCD4')), ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E5E7EB')), ('VALIGN', (0, 0), (-1, -1), 'TOP'), ('LEFTPADDING', (0, 0), (-1, -1), 4), ('RIGHTPADDING', (0, 0), (-1, -1), 4), ('TOPPADDING', (0, 0), (-1, -1), 3), ('BOTTOMPADDING', (0, 0), (-1, -1), 3)])); return t
MD = []
def md(t): MD.append(t)
S = [Spacer(1, 1.2 * cm), P('Orb v1 Race Twin: roadmap v3', ParagraphStyle('T', parent=ss['Title'], fontSize=26, leading=31, alignment=0)),
     P('Change the tyre. Replay the race. See where the time went. A validated single-car tyre-strategy counterfactual with an animated pace twin, built on the verified Orb v1 core, in three phases across three sittings, with seven workstreams, sealed evaluation and release gates.', ParagraphStyle('ST', parent=B, fontSize=11.5, leading=16, textColor=colors.HexColor('#374151'))),
     Spacer(1, 6), P('Team Orb v1 &middot; TrackShift 2026 &middot; drafted 12 September, 13:40 IST, for critique before any workstream starts.', SM), Spacer(1, 10)]
md('# Orb v1 Race Twin: roadmap v3\n\n*Drafted 12 Sep 13:40 IST for critique before any workstream starts.*\n')
# ---------- 0 programme ----------
S += [P('0. What we are building, in one paragraph', H1),
      P('The verified core stays untouched: one lock as the source of truth, the stint fixed-effects estimator, exact one- and two-stop enumeration, compound offsets, pit-loss handling, the post-race replay, and the 11-weekend, 29-case evidence base (0.023 against 0.137 s/lap, 28 of 29). On top of it we build the <b>Race Twin</b>: pick a race, a driver, an intervention lap, a compound and a continuation; the engine replays the driver\'s own race with only the tyre plan replaced, shows the lap-by-lap source of the difference, the cumulative elapsed-time delta with uncertainty, and two moving blips on the circuit. Three fidelity modes behind one interface: <b>tyre-only</b> (swap the curve, reset the age), <b>fixed-context</b> (add in-lap, pit loss, stationary time, out-lap, warm-up, safety-car rules, the rest of the plan; the scientifically strongest mode and the default), and <b>frozen-field</b> (rivals follow their observed race; the ghost catches traffic, takes dirty air, gets DRS, attempts passes sampled probabilistically; rival strategic responses are not simulated). The claim scope is written into every output: single-car, iso-context, virtual race-time position on the driver\'s own trajectory; never a predicted finishing position except in frozen-field mode, and there with a distribution.'),
      P('Wording that goes on the screen, verbatim: <i>Ghost Strategy Replay. A lap-by-lap estimate of how the same driver\'s race-time trajectory changes when only the tyre plan is replaced. Under fixed weather, flags and driver-and-car baseline, Orb v1 estimates the alternative plan would have completed the race N seconds sooner. Single-car pace counterfactual; rival reactions, overtakes and resulting traffic are not simulated in this mode. Generated from a pre-race model trained without this weekend; evaluated against a leave-one-driver-out Sunday reference.</i>', SM)]
md('## 0. Programme\nVerified core untouched. Race Twin on top: three fidelity modes (tyre-only, fixed-context default, frozen-field), claim scope written into every output.\n')
# ---------- 1 timeline ----------
S += [P('1. Sittings and anchors', H1),
      table([['Sitting', 'When (IST)', 'Scope', 'Anchors inside it'],
             ['1 (now)', 'Sat 13:45 to 23:30', 'Phase 0: one complete vertical slice, sealed holdout, contract, provider abstraction, parallel non-blocking work', 'Madrid FP3 refresh 17:30; qualifying refresh and hashed forecast 20:45; one timed rehearsal 22:30'],
             ['2', 'Sun 05:30 to presentation, then evening', 'Phase 1 before the slot: scale to all drivers of one race, hidden-stop validation aggregate, uncertainty, dashboard integration, demo path, two rehearsals. After the slot: the rest of Phase 1', 'Smoke test 08:00; presentation; Madrid race 18:30 and scorecard'],
             ['3', 'After the event', 'Phase 2: curve-provider improvements, frozen-field calibration, TUMFTM comparison, documents regenerated', 'Publish Madrid scorecard with the pre-race hash']], [1.7 * cm, 3 * cm, 7.2 * cm, 4.9 * cm]),
      P('Three-season download: 229 of about 350 sessions on disk at 12:30, eight workers, finishing about 15:00. Workstreams that need three seasons start after that; everything else starts on your go. The laptop is the only machine until then, so Phase 0 workstreams are limited to four concurrent processes.', SM)]
md('## 1. Sittings\n1: Sat 13:45-23:30 Phase 0 + Madrid anchors. 2: Sun 05:30-slot Phase 1 (before-slot subset), rest after. 3: post-event Phase 2.\n')
# ---------- 2 phase 0 ----------
S += [P('2. Phase 0, this sitting: one complete vertical slice', H1),
      P('Complete when the full experience works end to end for one race and one driver: select, choose lap and compound, compute the alternative race, show the cumulative delta with uncertainty, animate two blips, and pass the identity test. Mandatory items first; parallel items must not block; the "not tonight" list is enforced.'),
      P('2.1 Mandatory', H2),
      table([['#', 'Task', 'Owner', 'Accepted when'],
             ['0.1', 'Seal the holdout before anything is tuned: deterministic rule over metadata and feed-quality only (seed 2026, two races per season 2023 to 2025, stratified by circuit class, compound nomination, temperature, stop count, SC presence, at least one street circuit); write sealed_holdout_manifest.json and its sha256; builders never see per-race results', 'Workstream 3', 'Manifest and hash committed; prohibited_for_tuning true; selection reproducible from the rule'],
             ['0.2', 'Minimal lock v2 contract: pydantic models, exported JSON schema, additionalProperties false in stable blocks, extensions namespace, v1 to v2 adapter so every existing view still loads, golden fixture (one synthetic mini race, one historical race), atomic writes, sidecar layout with hashes', 'Workstream 1', 'Every downstream workstream works from the fixture; schema test passes on merge; no large arrays in the lock'],
             ['0.3', 'TyreCurveProvider interface with the current estimator as provider A: predict_curve(event, driver, compound, context, age_range) returning mean, q10, q50, q90, cliff probability, provenance', 'Workstream 2', 'Provider A reproduces the v1 curves exactly'],
             ['0.4', 'Counterfactual core, fixed-context and tyre-only modes: pace decomposition Y = B + T + P + I + e; intervention application; standardised pit event (circuit transit, expected stationary, compound out-lap, warm-up residual, as a distribution); SC and VSC handled as fixed observed schedule with SC-specific pit loss and frozen pace gains; contaminated laps reconstructed from the baseline, not copied', 'Workstream 2', 'Identity, same-compound, no-degradation, round-trip and time-accounting tests pass; one race and driver scenario compiles in under 250 ms'],
             ['0.5', 'Static lap-by-lap counterfactual table with the decomposition waterfall per lap', 'Workstream 2', 'Sum of lap deltas equals the finish delta'],
             ['0.6', 'Track geometry: canonical closed path by arc length from clean position traces with sector, corner type, DRS and pit flags; separate pit-lane polyline; unwrapped race distance S = lap x L + s; t_actual(S) from positions; t_cf(S) from the counterfactual laps; inversion to s(t) for both cars', 'Workstream 4', 'Actual-plan ghost overlays the real driver within one sample; pit trajectory renders'],
             ['0.7', 'Browser-side player as a Streamlit component: canvas, requestAnimationFrame, precompiled float32 frames, play, pause, 1x to 10x, lap scrubber, gap in seconds and metres, compound and age badges, median ghost with 10th to 90th percentile halo; Plotly frame animation as fallback', 'Workstream 4', 'Holds frame rate offline; scrubber deterministic'],
             ['0.8', 'Uncertainty: sample whole curves and parameters, never per-lap noise; pit loss, out-lap, warm-up, offsets, transfer uncertainty; precomputed quantiles; probability of gain; confidence status; outside-support warning', 'Workstream 2', 'Adjacent laps correlated; quantiles ordered'],
             ['0.9', 'Race Twin page added to the existing dashboard (no rebuild of the six views): control rail, map, evidence strip, lap decomposition, race-time chart with band, assumptions box, fidelity switch (frozen-field greyed until Phase 1)', 'Workstream 6', 'Loads from lock and hashed sidecars in under two seconds; runs offline'],
             ['0.10', 'Red team pass on the slice: leakage, joins, target-driver exclusion, identity test, SC handling, claim scope versus mode, lock and screen agreement', 'Workstream 7', 'blocking_issues.json empty'],
             ['0.11', 'Anchors: Madrid FP3 refresh, qualifying refresh, offsets from qualifying, forecast JSON and PDF with sha256 published; deck slide for the Race Twin with the wording above; one timed run', 'Lead', 'Hash posted before 21:45; run under five minutes']], [0.9 * cm, 8.5 * cm, 1.6 * cm, 5.8 * cm]),
      P('2.2 Parallel, non-blocking', H2)] + bullets([
      'Weather-only feature pass: per-lap track and air temperature, deltas over 5, 10, 20 minutes, humidity, wind, rainfall, a three-lap thermal proxy, load dose split, run phases, used-set flag, rename to tyre demand index. Writes new columns only; never blocks the slice.',
      'Hierarchical errors-in-variables Friday-to-Sunday regression on three seasons, chronological evaluation, cluster bootstrap by weekend, risk-coverage curve, information gate. Becomes provider B only if it beats provider A held out.',
      'Four-season downloads and the cleanup pass for failed sessions.']) + [
      P('2.3 Not tonight', H2)] + bullets(['Rebuilding the six dashboard views for aesthetics.', 'Driver league table.', 'Full TUMFTM integration.', 'Multi-agent track-position simulation.', 'Every advanced feature view.', 'Any attempt to make the liquid network win. It stays as the labelled ablation: temporal complexity did not beat stronger feature formulation.'])
md('## 2. Phase 0 (this sitting)\nSeal holdout; lock v2 contract + fixture + adapter; provider abstraction with current model as provider A; counterfactual core (fixed-context, tyre-only) with pit-event distribution and SC rules; identity/conservation tests; track geometry and time-warped two-blip player; uncertainty by whole-curve sampling; Race Twin page added to existing dashboard; red-team pass; Madrid anchors and hashed forecast.\nParallel non-blocking: weather features, EIV transfer model, downloads. Not tonight: dashboard rebuild, driver table, TUMFTM, multi-agent, LNN.\n')
# ---------- 3 phase 1 ----------
S += [Spacer(1, 6), P('3. Phase 1, second sitting: scale and validate', H1),
      table([['#', 'Task', 'Owner', 'Before or after the slot'],
             ['1.1', 'Compile all eligible drivers for one race, then the sealed holdout, then every 2026 race: scenario lattice driver x intervention lap x compound, per-lap arrays as compressed float32', 'Workstream 2', 'Before (one race), after (rest)'],
             ['1.2', 'Hidden-stop-response evaluation: for every actual stop in the holdout, hide post-stop laps, supply the actual intervention, predict the next 1, 3, 5 representative green laps; report MAE, cumulative error, coverage, by compound, circuit, new versus used set, green versus SC; state-space paper as benchmark', 'Workstream 3', 'Before (aggregate only), per-race after freeze'],
             ['1.3', 'Strategy regret under a post-race reference: pre-race plan, oracle plan under the reference, regret; Orb v1, naive, observed and default plans; median, mean, worst decile, within 2, 5, 10 s; probabilities', 'Workstream 3', 'After'],
             ['1.4', 'Leave-one-driver-out race audit: the target driver excluded from the Sunday reference used to score them', 'Workstream 3', 'Before'],
             ['1.5', 'Frozen-field simulator: rivals on observed trajectories; following-loss model from historical gaps and corner exposure; overtake probability from observed overtake opportunities (OpenF1 overtakes, 2023 onward); Monte Carlo interaction; position distribution; SC-neutral and SC-aware outputs with warning', 'Workstream 5', 'After; fixed-context is the fallback'],
             ['1.6', 'RaceEventSource abstraction: replay, live, recorded-live sources emitting the same events; race-day mode with recursive Bayesian updating that can widen (explicit process noise, resets at stops); alerts as band departures', 'Workstream 2', 'After'],
             ['1.7', 'Dashboard: fidelity switch live, rival blips, position distribution, validation view for hidden-stop and regret, historical replay controls, prospective Madrid case', 'Workstream 6', 'Partly before'],
             ['1.8', 'Documents regenerated from lock v2; questions extended; demo path rehearsed twice', 'Lead', 'Before']], [0.9 * cm, 9.6 * cm, 1.6 * cm, 4.7 * cm])]
md('## 3. Phase 1 (sitting 2)\nScale scenarios; hidden-stop-response evaluation; strategy regret vs oracle; leave-one-driver-out audit; frozen-field simulator (fallback fixed-context); event-source abstraction and race-day updating that can widen; dashboard integration; documents.\n')
# ---------- 4 phase 2 ----------
S += [P('4. Phase 2, third sitting: improve the curve provider', H1), P('Because the Race Twin consumes only the provider interface, model experiments cannot break the product. In order:')] + bullets([
      'Absolute compound identity (C1 to C5 from Pirelli nominations) alongside weekend role, season as a prior not a pool.', 'Track-temperature and thermal-memory state; shape-constrained wear curve, monotone in load dose; Friday diagnosed, Sunday constrained.',
      'Hierarchical or state-space live estimator with explicit process noise.', 'XGBoost or CatBoost residual benchmark with weekend-grouped validation, same inputs for every model.', 'Better pit-loss and warm-up model per circuit and compound.',
      'Corner-weighted spatial delta from the tyre-demand index; corner-specific time-gap traffic (re-extraction).', 'TUMFTM race simulation fed with our distributions as a second benchmark; the GECCO evolutionary repository for magnitude sanity checks.',
      'Multi-agent simulation only after everything above. Driver rankings only as conditional residuals with teammate-within-weekend comparisons, minimum stint counts, shrinkage intervals and repeatability.', 'The liquid network only as an optional high-frequency thermal-state encoder, compared with hand features and an EWMA; kept only if it wins held out.'])
md('## 4. Phase 2 (sitting 3)\nAbsolute compounds; thermal state and shape-constrained wear; state-space live estimator; boosted residual benchmark; pit-loss model; spatial delta; traffic; TUMFTM; multi-agent last; LNN optional encoder.\n')
# ---------- 5 workstreams ----------
S += [PageBreak(), P('5. Workstreams, ownership and integration', H1),
      table([['Workstream', 'Owns', 'Builds', 'Accepted when'],
             ['1 Contract and fixtures', 'schemas/, fixtures/, validators/', 'lock_v2 schema, mini synthetic race, golden historical race, validator, v1 adapter, atomic writes', 'Downstream workstreams work from the fixture; optional and missing values tested; no large arrays in the lock'],
             ['2 Counterfactual core', 'counterfactual/', 'Decomposition, interventions, pit and out-lap effects, SC rules, Monte Carlo, modes, provider interface, event sources, identity tests', 'Actual plan gives zero delta; deterministic tests pass; scenario under 250 ms'],
             ['3 Blind evaluation', 'evaluation/holdout/', 'Sealed selection, hidden-stop-response, regret, calibration, paired weekend bootstrap, scorecard', 'Builders cannot see per-race holdout results; every metric weekend-grouped; naive, current and new compared; results enter the lock automatically'],
             ['4 Geometry and animation', 'replay/, dashboard/components/race_twin/', 'Canonical path, pit lane, time warping, browser player, Plotly and static fallbacks', 'Actual-plan ghost overlays the driver; pit path renders; frame rate offline'],
             ['5 Frozen field', 'interaction/', 'Rival trajectories, following loss, DRS and passing zones, overtake probability, position distribution', 'Observed plan reconstructs observed ordering; disabling interactions reproduces fixed-context; passing calibrated held out; no impossible overlaps'],
             ['6 Dashboard', 'app_v2 route, views/', 'Controls, map, waterfall, delta chart, assumptions banner, validation view, fidelity switch', 'No training in the dashboard; every number from lock or hashed asset; under two seconds; offline replay completes'],
             ['7 Red team', 'none', 'red_team_report.json, blocking_issues.json, claim_evidence_map.json', 'No release with a blocking issue']], [2.6 * cm, 3.1 * cm, 5.7 * cm, 5.4 * cm]),
      P('Integration rules', H2)] + bullets(['Each workstream writes only inside the directories it owns; shared code changes go through the lead.', 'Every merge runs the schema validator, the identity tests and the release gates; a failed gate blocks the merge.', 'Every number reaches a slide only through the lock; documents are regenerated, never edited.', 'Workstreams run at most four concurrent heavy processes until the download finishes at about 15:00.', 'A claim on a screen may not exceed the fidelity mode selected; the claim_scope field is rendered, not paraphrased.'])
md('## 5. Workstreams\n1 contract/fixtures; 2 counterfactual core (+ provider, event sources); 3 blind evaluation; 4 geometry/animation; 5 frozen field; 6 dashboard; 7 red team. Ownership by directory; gates on every merge; claims bound to mode.\n')
# ---------- 6 contracts ----------
S += [P('6. Contracts', H1), P('6.1 Lock as manifest, sidecars by hash', H2),
      P('out/lock_v2.json holds headline numbers, schema and model versions, git sha, data cutoff, model hashes, training and exclusion lists, forecast summaries, gate results, strategy summaries, counterfactual summaries, and the paths and sha256 of sidecar files. Per-lap features, position traces, animation frames, per-driver counterfactuals and bootstrap samples live in out/features/, out/counterfactual/, out/maps/, out/validation/ as Parquet, npz or compressed float32, referenced by hash. Every block carries schema_version, generated_at, data_cutoff, git_sha, model_version, model_hash, training_weekends, excluded_weekends, units, provenance, assumptions, support_status, quality_status. Every counterfactual additionally carries claim_scope = single_car_iso_context, track_position_simulated, rival_interactions_simulated, traffic_mode (clean_air or paired_replay or frozen_field), safety_car_schedule = historical_fixed.', SM),
      P('6.2 Interfaces', H2),
      P('TyreCurveProvider.predict_curve(event_id, driver_id, compound, context, tyre_age_range) -> CurveDistribution(mean_loss_s, q10_loss_s, q50_loss_s, q90_loss_s, cliff_probability, provenance)', MONO),
      P('RaceEventSource.events() -> RaceEvent(position_update | lap_completed | pit_entry | pit_exit | weather_update | track_status | overtake | retirement | feed_quality_warning); implementations Replay, Live, RecordedLive', MONO),
      P('6.3 Mandatory per-lap columns of a counterfactual sidecar', H2),
      P('lap, actual_lap_time, cf_lap_time_mean, cf_lap_time_q10, cf_lap_time_q90, lap_delta, cumulative_delta, actual_compound, cf_compound, actual_tyre_age, cf_tyre_age, actual_traffic_effect, cf_traffic_effect, pit_state, track_status, actual_position, cf_position_median, cf_position_q10, cf_position_q90', MONO)]
md('## 6. Contracts\nLock as manifest; sidecars by hash; mandatory metadata per block; claim-scope fields per counterfactual; TyreCurveProvider and RaceEventSource interfaces; mandatory per-lap columns.\n')
# ---------- 7 validation ----------
S += [PageBreak(), P('7. Validation layers and wording rules', H1),
      table([['Layer', 'What it tests', 'Reported as'],
             ['Identity and invariance', 'Actual plan gives zero delta; same-compound swap gives zero; zero degradation gives offset plus stop effects only; round trip returns to zero; sum of lap deltas equals finish delta; one stop creates exactly one entry, one stationary event, one exit, one age reset, one warm-up', 'CI results on every build'],
             ['Hidden-stop-response', 'For real stops in unseen weekends: predict the next 1, 3, 5 representative laps given the actual intervention', 'MAE, cumulative error, interval coverage, by compound, circuit, set status, flag state; versus naive fresh-tyre assumption and the state-space baseline'],
             ['Strategy regret', 'Pre-race plan versus the hindsight oracle under a post-race reference; Orb v1, naive, observed, default', 'Median, mean, worst decile, within 2, 5, 10 s; probabilities; "held-out strategy replay under a post-race reference model"'],
             ['Sealed holdout', 'Whole weekends chosen by a deterministic metadata rule before tuning; hash committed; per-race results released only after freeze; later tuning flagged post_holdout_tuning', 'Aggregate scorecard, weekend-grouped bootstrap'],
             ['Prospective', 'Madrid forecast published with hash before the race; scored after', 'Scorecard beside the hash']], [3 * cm, 8.2 * cm, 5.6 * cm]),
      P('Wording rules: the race estimate is a "race-derived pace-loss reference", never ground truth or actual wear; a positive counterfactual is a "model-implied gain", never observed race time saved; "untouched" is reserved for the sealed holdout and the prospective race; the 29 existing cases are the "cross-validated historical sample"; a Friday showing no positive slope is "inconsistent with a wear-only interpretation", not impossible; the proxy is a "tyre demand index"; novelty claims read "in the public methods we reviewed, we did not find...".', SM)]
md('## 7. Validation layers\nIdentity/invariance; hidden-stop-response; strategy regret vs oracle; sealed holdout (deterministic, hashed, per-race results after freeze); prospective Madrid. Wording rules for reference, model-implied gain, untouched, demand index, novelty.\n')
# ---------- 8 degradation ----------
S += [P('8. Graceful degradation', H1),
      table([['Failure', 'Automatic downgrade', 'Still shown'],
             ['Live feed unavailable', 'Recorded event replay', 'Full live-style demonstration'], ['Position feed corrupted', 'Canonical centreline', 'Two-blip progress by arc length'], ['Frozen-field unavailable', 'Fixed-context mode', 'Valid elapsed-time counterfactual'],
             ['New transfer model fails', 'Provider A', 'Race Twin unchanged'], ['Monte Carlo too slow', 'Precomputed quantiles', 'Probability and bands'], ['JavaScript map fails', 'Plotly lap-level animation', 'Actual and ghost visible'],
             ['All animation fails', 'Pre-rendered local video plus charts', 'Complete demo'], ['SC complexity', 'Green-flag or fixed-SC mode', 'Labelled restricted result'], ['Compound mapping missing', 'Role curve with wider interval', 'No silent guess'], ['Set age ambiguous', 'Scenario range over plausible ages', 'Wider uncertainty']], [4.2 * cm, 5.4 * cm, 7.2 * cm])]
md('## 8. Graceful degradation\nEvery ambitious component has an automatic downgrade; the demo never depends on a single component.\n')
# ---------- 9 gates ----------
S += [P('9. Release gates, non-negotiable', H1)] + bullets(['Actual strategy produces zero counterfactual delta.', 'No race data used in pre-race predictions (forecast_cutoff, source_hash, uses_race_data false).', 'Every intervention resets tyre age; pit loss appears exactly once; in-lap and out-lap never double-counted.', 'SC and VSC mode explicitly identified.', 'Target driver excluded from the evaluation reference.', 'Role and absolute compound identities valid where present.', 'Weekend-level holdout grouping preserved; all quantiles ordered.', 'Map and numerical cumulative delta agree; actual-plan animation aligns with actual timing.', 'Every asset hash resolves; dashboard and deck read the same lock; offline replay completes.', 'Property tests over random plans: no negative age, no overlapping stints, no illegal plan, no pit after the finish, positions within the field, cumulative equals sum, changing nothing changes nothing.'])
md('## 9. Release gates\nIdentity; no leakage; single pit loss; SC mode; target-driver exclusion; compound validity; grouping; quantile order; map equals numbers; hashes; same lock; offline; property tests.\n')
# ---------- 10 demo ----------
S += [PageBreak(), P('10. The five-minute path', H1)] + bullets(['Saturday forecast on screen: "locked before the race", hash, band, gate.', 'Select a real driver and intervention: "instead of staying out on the hard to lap 31, pit on lap 24 for medium."', 'Start the Race Twin: the ghost pits, falls behind, recovers.', 'Stop on a decisive lap; the waterfall: "the new tyre gains 0.63 s here, 0.21 lost behind traffic, net 0.42."', 'Resume; in frozen-field mode the position distribution moves when the ghost meets a rival.', 'Final output: median gain, probability of gain, frozen-field finish estimate with its range.', 'Open the sealed validation: hidden post-stop laps in unseen weekends, predicted response, strategy regret.', 'End with the limitation: rivals keep their observed strategy; tyre, pit, traffic and passing are modelled, strategic reactions are not.'])
md('## 10. Demo path\nForecast with hash -> intervention -> ghost replay -> waterfall on a decisive lap -> position distribution -> final numbers -> sealed validation -> limitation.\n')
# ---------- 11 risks ----------
S += [P('11. Where we might still go wrong', H1)] + bullets([
      'Sealing the holdout after looking at counterfactual results would invalidate it; it is task 0.1 and happens before any counterfactual code runs.',
      'The frozen-field overtake model needs observed overtake opportunities; OpenF1 exposes them from 2023, but calibration on a few hundred events is thin. It ships behind the fallback and its probabilities carry intervals.',
      'The standardised pit event replaces the observed stop by design, so the identity test is exact only when the standardised stop is disabled; the test must run in both configurations.',
      'The JavaScript component must run inside Streamlit\'s iframe offline; the Plotly fallback is tested first, not last.',
      'The three-season regression may lose to the 2026 ratio because 2026 is a regime change; it becomes provider B only by held-out error, and the deck says which provider produced each number.',
      'Recursive updating with tiny process noise becomes overconfident; process noise, resets and widening rules are written down before the first live number is shown.',
      'The laptop runs eight download workers until about 15:00; heavy workstreams before then slow everything, including the FP3 refresh.',
      'Rehearsal is a release gate too: no new feature enters the demo path after the second timed run on Sunday morning.'])
md('## 11. Risks\nHoldout sealed first; frozen-field thin calibration behind fallback; identity test in both pit configurations; JS component offline; regime change; overconfident filters; CPU until 15:00; rehearsal as a gate.\n')
# ---------- 12 questions ----------
QA = [('How do you validate something that never happened?', 'We validate the parts that did happen: for every real tyre change in sealed weekends we hide the laps after the stop, predict the response, and score it. Unchosen strategies are reported as model-implied counterfactuals under a held-out post-race reference, with regret against the hindsight oracle, never as observed outcomes.'),
      ('Is it not circular to pick the plan and score it with the same model?', 'The pre-race policy and the post-race scorer are separated. The target weekend is excluded from training, the target driver is excluded from the Sunday reference where data allows, and the holdout was sealed by a metadata rule before this layer was tuned.'),
      ('Why does a different stop not change traffic?', 'In fixed-context mode it does not, by construction, and the screen says so. Frozen-field mode adds traffic, dirty air, DRS and passing against rivals on their observed trajectories; what it still does not simulate is rivals changing strategy in response.'),
      ('Is the second dot physically simulated?', 'Its timing is modelled; its geometry is the driver\'s own recorded trajectory projected onto track distance and time-warped. It is a pace twin, not a vehicle-dynamics simulation, and the pit lane uses the recorded pit path.'),
      ('Do you use race data in the pre-race recommendation?', 'No. Every pre-race scenario carries a forecast cutoff and a hash; race data enters only afterwards, for scoring and audit.'),
      ('Why can the ghost be ahead on the map but not "in P6"?', 'Because in fixed-context mode the map shows virtual race-time position on the driver\'s own trajectory. Position claims are made only in frozen-field mode, and there as a distribution with its range.'),
      ('What is the uncertainty on the ghost?', 'Whole curves and parameters are sampled, not per-lap noise, so adjacent laps stay correlated: degradation curve, transfer, pit loss, out-lap, warm-up, offsets, and in frozen-field mode passing outcomes. The halo is the 10th to 90th percentile of the ghost\'s position; the readout gives the probability of gain.'),
      ('How large is the untouched sample, really?', 'It is counted in races and driver-race cases, not telemetry rows. The sealed holdout is at least six whole weekends from 2023 to 2025, chosen by rule; the prospective case is Madrid. The 29 existing cases are cross-validated, and we call them that.'),
      ('What happens under a safety car?', 'The observed schedule is fixed in both worlds. Normal pace gains are frozen during controlled laps, thermal state keeps updating, pit loss switches to the SC value, and a restart warm-up applies. An SC-aware mode that recomputes the stop decision carries a warning because restart traffic would differ.'),
      ('If the frozen-field simulator is not calibrated by Sunday, what do we show?', 'Fixed-context mode, which is the scientifically strongest one anyway, with the elapsed-time delta, its band and the probability of gain. The fidelity switch shows frozen-field as unavailable rather than pretending.')]
S += [P('12. Ten questions this feature must survive', H1)]
for i, (q, a) in enumerate(QA, 1): S += [KeepTogether([P(f'<b>{i}. {q}</b>', B), P(a)])]
md('## 12. Ten questions\n' + '\n'.join(f'**{i}. {q}**\n\n{a}\n' for i, (q, a) in enumerate(QA, 1)))
doc = SimpleDocTemplate('out/Orb_v1_Roadmap_v3.pdf', pagesize=A4, leftMargin=1.8 * cm, rightMargin=1.8 * cm, topMargin=1.6 * cm, bottomMargin=1.6 * cm, title='Orb v1 Race Twin roadmap v3', author='Team Orb v1')
def footer(c, d): c.saveState(); c.setFont('Helvetica', 7.5); c.setFillColor(colors.HexColor('#6B7280')); c.drawString(1.8 * cm, 1 * cm, 'Orb v1 Race Twin · roadmap v3 · draft for critique'); c.drawRightString(A4[0] - 1.8 * cm, 1 * cm, str(d.page)); c.restoreState()
doc.build(S, onFirstPage=footer, onLaterPages=footer); open('out/ROADMAP_v3.md', 'w').write('\n'.join(MD)); print('built')
