"""Orb v1: the case. Idea, stack, outcomes, why we win -> out/Orb_v1_The_Case.pdf and out/THE_CASE.md"""
import json, re
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image, KeepTogether
L = json.load(open('out/lock.json')); V = L['validation']; m = V['mae_all_with_fallback']; mi = V['mae_issued']; cal = V['calibration']; bc = V['by_compound']
ss = getSampleStyleSheet()
H1 = ParagraphStyle('H1', parent=ss['Heading1'], fontSize=18, leading=22, spaceBefore=8, spaceAfter=8)
H2 = ParagraphStyle('H2', parent=ss['Heading2'], fontSize=12.5, spaceBefore=9, spaceAfter=4)
B = ParagraphStyle('B', parent=ss['BodyText'], fontSize=10.2, leading=14.5, spaceAfter=6)
SM = ParagraphStyle('SM', parent=B, fontSize=8.6, leading=11.5, textColor=colors.HexColor('#4B5563'))
BUL = ParagraphStyle('BUL', parent=B, leftIndent=13, bulletIndent=2, spaceAfter=3)
CELL = ParagraphStyle('CELL', parent=B, fontSize=8.6, leading=11, spaceAfter=0); CELLB = ParagraphStyle('CELLB', parent=CELL, fontName='Helvetica-Bold')
def P(t, s=B): return Paragraph(t, s)
def bullets(items): return [Paragraph(t, BUL, bulletText='•') for t in items]
def table(rows, widths):
    data = [[Paragraph(str(c), CELLB if i == 0 else CELL) for c in r] for i, r in enumerate(rows)]
    t = Table(data, colWidths=widths, repeatRows=1); t.setStyle(TableStyle([('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#C7CCD4')), ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#E5E7EB')), ('VALIGN', (0, 0), (-1, -1), 'TOP'), ('LEFTPADDING', (0, 0), (-1, -1), 4), ('RIGHTPADDING', (0, 0), (-1, -1), 4), ('TOPPADDING', (0, 0), (-1, -1), 3), ('BOTTOMPADDING', (0, 0), (-1, -1), 3)])); return t
def fig(path, w, cap):
    im = Image(path); r = im.imageHeight / im.imageWidth; im.drawWidth = w * cm; im.drawHeight = w * cm * r; return KeepTogether([im, Spacer(1, 2), P(cap, SM)])
MD = []  # markdown mirror
def md(t): MD.append(t)
S = []
S += [Spacer(1, 1.6 * cm), P('Orb v1: the case', ParagraphStyle('T', parent=ss['Title'], fontSize=28, leading=34, alignment=0)),
      P('The idea in depth, the technology stack and why each piece was chosen, the outcomes with every number from the locked results, the argument for winning mapped to the five judging criteria, the honest risks, and ten questions a jury will ask.', ParagraphStyle('ST', parent=B, fontSize=12, leading=16.5, textColor=colors.HexColor('#374151'))),
      Spacer(1, 8), P(f'Team Orb v1 &middot; Samuel Christ &middot; TrackShift 2026, Tyre Degradation Intelligence &middot; Plaksha University &middot; numbers from lock {L["generated_at"]} IST, {V["n_weekends"]} scored weekends, {V["n_compound_weekends"]} compound-weekends, all leave-one-weekend-out.', SM), PageBreak()]
md('# Orb v1: the case\n')
# ---------------- 1 idea ----------------
S += [P('1. The idea', H1),
      P('<b>The question a strategist asks on Saturday night.</b> How much slower will each tyre compound be after twenty laps on Sunday, at what age does the harder tyre become the better one, and should we stop once or twice? Every one of those is a question about the degradation curve, seconds of lap time lost per lap of tyre age, per compound. Get it wrong by a factor of seven, which is what a straight line through Friday laps did at Hungary this year, and the plan loses more than a pit stop.'),
      P('<b>Why it is hard.</b> The only evidence before the race is Friday practice, and a Friday lap is not a tyre measurement. It mixes five things: the tyre wearing, fuel burning off (about 1.1 kg per lap, worth about 0.03 s per lap, pulling the opposite way to wear), the track getting grippier as rubber goes down (0.6 s per hour at Madrid on Friday), traffic, and the driver, who warms up, learns the track, pushes harder or eases off. Strip those and you still do not have Sunday, because drivers attack tyres on Friday and nurse them on Sunday. Friday lies twice: about what the tyre did, and about what it will do.'),
      P('<b>The insight.</b> Treat Friday as a biased sample of the race and model the bias instead of pretending it is not there. The first lie is removable with physics and telemetry, lap by lap. The second lie is not measurable on Friday, but it is learnable from earlier weekends, because the same estimator run on race laps tells you how much Sunday shrank Friday last time, per compound. And when Friday carries no signal at all, the right output is a refusal with a fallback, not a guess.'),
      P('<b>The system, in six verbs.</b> Ingest every lap of every session from the public timing feed. Clean each lap: drop what cannot be trusted, compare every run only to itself, subtract the known fuel effect and the measured track evolution. Gate: issue a curve only with at least thirty clean long-run laps and a positive cleaned slope. Learn: the per-compound ratio of Sunday to Friday from previous weekends, applied only where weekends agree. Forecast: the race curve with a band, crossover laps, one stop versus two. Score: on Sunday night, the same estimator on the race laps, and the miss published whatever it says.'),
      P('<b>The discovery that came out of it.</b> Some Fridays show a tyre getting faster with age, which is impossible. Our energy proxy, computed from the public speed and position traces, showed why: on every such Friday the driver was ramping up, energy through the tyre rising through the run. That is a fifth confounder, the push profile, that no published method removes. Decomposing the Friday-to-Sunday gap on the issued cases, the push profile explains a median 52% of it (68% pooled over eight cases); the learned management factor covers the rest. The second lie now has an anatomy.'),
      P('<b>Why it is an idea and not a pipeline.</b> In machine-learning language it is domain shift with a learned scalar correction, selective prediction with a validated abstention rule, and evaluation strictly out of distribution, on weekends the model never saw. In racing language it is a Friday curve you can bet a pit stop on, and a tool that tells you when you cannot.')]
md('## 1. The idea\nFriday lies twice. We remove the first lie with physics and telemetry, learn the second from earlier weekends, refuse when Friday has no signal, and score ourselves against the race. The push profile, measured from telemetry energy, explains about half of the Friday-to-Sunday gap; the learned management factor covers the rest.\n')
# ---------------- 2 stack ----------------
S += [P('2. The technology stack, and why each piece', H1),
      table([['Layer', 'What', 'Why this choice'],
             ['Data', 'FastF1 3.8 over Formula 1\'s live-timing archive; OpenF1 for cross-checks; Pirelli nominations; FIA documents', 'Free, public, every session since 2018, 3.7 Hz telemetry including gap to the car ahead. Reproducible by anyone, usable by categories without private sensors.'],
             ['Data on disk', '2026: all fourteen rounds that exist, every session. 2025, 2024, 2023: all rounds, downloading today (about 350 sessions, 14 GB)', 'Three seasons of same-track history to test whether the Sunday factor is a property of the circuit or of the 2026 car.'],
             ['Features (features.py)', 'Per lap: times, sectors, tyre age and compound, flags, deleted laps, pit laps, traffic share within 60 m, a tyre-energy proxy on a 10 m arc-length grid, feed-quality counters', 'The energy proxy is the only public route to the driver\'s push; the quality counters catch feeds that are degraded at source (Hungary race, China FP1) so they are refused rather than modelled.'],
             ['Estimator (model_v2.py)', 'Stint fixed-effects regression: lap time = stint constant + compound slope x age + fuel prior + measured evolution; identical on practice and race', 'Identifiable, auditable, and symmetric, so the Friday-to-Sunday ratio is a property of the data, not of the method. Fuel is a prior because inside a run fuel and age are collinear.'],
             ['Pipeline (pipeline.py)', 'Every weekend to one lock file: gate, leave-one-weekend-out factors, low-degradation fallback, bands, push diagnostic, validation, live forecasts, strategy', 'One source of truth. Dashboard, brief and deck read it and compute nothing, so no number on a screen can contradict a slide.'],
             ['Strategy (strategy2.py)', 'Compound offsets from qualifying with a plausibility rule, pit loss, every one- and two-stop plan enumerated, crossover laps, replay scored under race-observed curves', 'A curve only matters as a decision; the replay ranks Friday views by the seconds they cost.'],
             ['Learning', 'Transfer factor per compound with an agreement rule; bootstrap intervals; sensitivity sweep over every stated choice', 'Learned on training weekends, scored on held-out ones, with the uncertainty shown.'],
             ['Liquid model (liquid.py)', 'Closed-form continuous-time cell (ncps, PyTorch) reading each race stint lap by lap; held-out stints; fair ablation against a linear model with the same inputs', 'Tested the fashionable thing honestly. It did not beat the line; the per-lap inputs did, by 23%. Kept as the curve-shape tool.'],
             ['Dashboard (app.py)', 'Streamlit and Plotly, six URL-addressable views', 'Fast to build, runs offline from cached data, deep links for the demo, static HTML fallback.'],
             ['Documents', 'Deck, manual, explainer and this case generated by scripts from the lock (matplotlib, reportlab)', 'Regenerated, never hand-edited, when a number changes.'],
             ['Environment', 'Python 3.12 in a uv-managed virtual environment, pinned requirements, refresh script for new sessions', 'One command rebuilds everything for any Grand Prix by name on a laptop.']], [2.8 * cm, 6.6 * cm, 7.4 * cm]), PageBreak()]
md('## 2. Stack\nFastF1 data; per-lap features incl. an energy proxy and feed-quality checks; stint fixed-effects estimator identical on practice and race; pipeline to a single lock file; strategy replay; learned transfer factors with bootstrap and sensitivity; liquid-network ablation (ncps/PyTorch); Streamlit dashboard; documents generated from the lock.\n')
# ---------------- 3 outcomes ----------------
S += [P('3. Outcomes, with the numbers', H1),
      table([['Result', 'Number', 'Meaning'],
             ['Naive straight line, error against the race', f'{m["naive"]:.3f} s/lap', 'What a team gets by drawing a line through Friday laps'],
             ['Orb v1, error against the race, all cases', f'{m["clearstint"]:.3f} s/lap', f'90% interval {V["ci90_mae_clearstint_all"][0]:.3f} to {V["ci90_mae_clearstint_all"][1]:.3f}; six times better'],
             ['Correlation with the race', f'{cal["naive"]["r"]:.2f} naive, {cal["all_with_fallback"]["r"]:.2f} Orb v1', 'Calibration slope 0.77; the curve transfers once Sunday management is learned'],
             ['Cases where Orb v1 beats naive', f'{V["wins_clearstint_over_naive"]} of {V["n_compound_weekends"]}', 'Not a fluke of one weekend'],
             ['Issued vs withheld', f'{V["n_issued"]} issued, {V["n_withheld"]} withheld', 'Every withheld case was a low-degradation race; fallback error 0.028 vs 0.082 naive'],
             ['Per compound, Orb v1 error', f'soft {bc["SOFT"]["mae_clearstint"]:.3f}, medium {bc["MEDIUM"]["mae_clearstint"]:.3f}, hard {bc["HARD"]["mae_clearstint"]:.3f}', f'Transfer factors: soft x{bc["SOFT"]["k_median"]:.2f}, medium x{bc["MEDIUM"]["k_median"]:.2f}, hard not applied'],
             ['Push profile explains the gap', 'median 52%, pooled 68% (8 cases)', 'The fifth confounder is measured, not assumed'],
             ['Sensitivity of the headline', '0.021 to 0.027 s/lap', 'Across fuel prior 0.9 to 1.3 kg/lap, 0.025 to 0.035 s/kg, traffic 20 to 40%, runs 4 to 7 laps'],
             ['Strategy replay, ten races', 'naive costs 0 to 155 s; Orb v1 0 to 55 s', 'Orb v1 beats naive on 7 of 8 conventional races; Barcelona is the miss'],
             ['Liquid network, held-out', 'beats best baseline 10 of 31', 'Inputs +23%; network on top of the same inputs about 0'],
             ['Madrid, live', 'soft +0.098 (band -0.10 to +0.30); medium withheld, forecast +0.028', 'Issued from FP1 and FP2, refreshed after FP3 and qualifying, hashed before the race'],
             ['Data assets', '2026 complete (67 session files); 2023 to 2025: 229 of about 350 sessions on disk at 12:27 IST, finishing mid-afternoon', 'Three seasons of same-track history for the transfer-factor prior; three session-level failures only, all retried']], [5 * cm, 4.4 * cm, 7.4 * cm]),
      Spacer(1, 6), fig('out/simple_fig3.png', 13, 'The headline test: every weekend predicted without seeing its own race.'),
      P('What exists as software today: the pipeline and lock, the six-view dashboard, the strategy layer, the liquid-model test, the deck, the manuals, and the live Madrid forecast. What remains today is refreshes, the three-season prior, and rehearsal.')]
md(f'## 3. Outcomes\nNaive {m["naive"]:.3f} vs Orb v1 {m["clearstint"]:.3f} s/lap; r {cal["naive"]["r"]:.2f} -> {cal["all_with_fallback"]["r"]:.2f}; {V["wins_clearstint_over_naive"]}/{V["n_compound_weekends"]} wins; {V["n_withheld"]}/{V["n_withheld"]} withheld were low-degradation races; push profile explains ~half the gap; sensitivity 0.021-0.027; Madrid live.\n')
# ---------------- 4 why we win ----------------
S += [PageBreak(), P('4. Why we win, criterion by criterion', H1),
      table([['Criterion', 'Weight', 'What we bring', 'What the field brings'],
             ['Technical depth and innovation', '30%', 'A measured fifth confounder nobody else strips; a learned, validated transfer factor; a validated abstention rule; a fair ablation of a liquid network; sensitivity on every stated choice; 29 held-out cases', 'Regressions on one weekend, gradient boosting on synthetic data, or, in PITWALL\'s case, real rigour that concluded the curve cannot be delivered'],
             ['Problem-solution fit', '25%', 'The literal brief: clean practice curves plus a post-race validation tool, every compound, every weekend, with refusal where honest', 'Simulators, replays of 2023 Bahrain, decision engines that "do not predict tyres"'],
             ['Demo and working prototype', '20%', 'Six views on real data, a live weekend, a forecast on record before the race', 'Prettier screens on synthetic or in-sample numbers'],
             ['Scalability and real-world viability', '15%', 'One command per Grand Prix from free data; the customer is every category without private sensors: F2, F3, F1 Academy, Indian F4, broadcasters; the loop transfers to any confounded wear problem', 'Mostly F1-only framing or none'],
             ['Presentation', '10%', 'One story, Friday lies twice, told in five minutes with the scorecard on screen; every number regenerated from one file', 'Varies']], [3.2 * cm, 1.3 * cm, 6.2 * cm, 6.1 * cm]),
      P('The structural reason', H2),
      P('The rubric rewards fit and honesty as much as sophistication. The strongest rival matched our rigour and then walked away from the brief; the flashiest rivals cannot show a held-out number. We are the only entry that delivers the literal ask, scores it across a season, says "withheld" when it should, and puts a live forecast on record. That combination is worth more than any single model.'),
      P('Why we might not, and what we do about it', H2)] + bullets([
      'A solo presenter against teams of four. Answer: a scripted five-minute path with URL deep links, three timed runs tonight, two tomorrow, and the manual\'s thirty-plus questions rehearsed.',
      'Thirteen of 29 compounds withheld reads as "works when it works". Answer: say early that withheld is a forecast, and that it was right thirteen times out of thirteen.',
      'PITWALL in the room saying practice curves do not transfer. Answer: their test is on pit-stop deltas whose noise equals the signal; at the strategist\'s unit the correlation is 0.78, and here are 29 held-out cases.',
      'The fuel effect is assumed. Answer: the sensitivity sweep, and the fact that PITWALL\'s own race-data estimate, 0.0294 s per kg, sits inside it.',
      'Madrid could miss on Sunday night. Answer: that is the point of a real forecast; the score is published either way, hash beside it.',
      'The venue network or the API. Answer: the pipeline and dashboard run offline; the static export covers the rest.'])
md('## 4. Why we win\nTechnical depth: measured fifth confounder, learned and validated factor, validated abstention, fair ablation. Fit: the literal brief delivered. Demo: real data, live weekend. Scalability: any GP from free data; junior series and broadcasters. Presentation: one story, one file.\n')

# ---------------- 6 race-day mode and tyre-state quantities ----------------
S += [PageBreak(), P('6. Race-day mode and the five tyre-state quantities', H1),
      P('A strategist wants the tyre state during the race, not only on Friday. Public data supports some of it, as measured quantities or honest proxies, and does not support the rest. We build the first group and refuse the second, with a labelled socket where a team\'s own sensors would plug in.'),
      table([['Quantity', 'From public data?', 'How, and the honest label', 'Build cost'],
             ['Real-time traction coefficient', 'Proxy only', 'Per corner, apex speed squared is proportional to available lateral grip at that corner. Tracked lap by lap within a stint it gives a grip index that falls as the tyre goes off. Friction cannot be separated from downforce without the car\'s aero map, so it is a grip index, not a coefficient.', 'About 2 h; live-capable'],
             ['Wear rate and remaining tread depth', 'No', 'Tread depth is not observable in any public feed; only Pirelli measures it after a run. A "remaining depth" figure from timing data is a formula wearing a physical unit. Refused, with the reason on screen.', 'Socket for team data'],
             ['Performance loss per lap, tyre only, live', 'Yes', 'The estimator run recursively on the current stint as laps arrive from the live-timing stream: fuel, evolution and traffic stripped, slope re-estimated every lap and compared with the Friday forecast band.', 'About 3 h; demonstrated as a lap-by-lap replay; runs for real on Sunday'],
             ['Tyre energy and laps of useful life remaining', 'Yes', 'Energy per lap exists. Useful life is laps until the forecast pace loss crosses the crossover to the next compound, or the cliff lap where the shape model finds one, reported as a range from the band.', 'About 1 h'],
             ['Puncture risk or structural integrity', 'No', 'Punctures come from debris, kerb strikes and pressure excursions, none public; failures are a handful per season, so no index could be validated. Refused.', 'Socket for team data']], [3.3 * cm, 2.1 * cm, 8.4 * cm, 3 * cm]),
      P('Race-day mode, as designed', H2)] + bullets([
      '<b>Pre-race plan.</b> The whole race mapped lap by lap: compound sequence, stint lengths, crossover laps, the pit window (the range of laps within a few seconds of optimal), and a probability that one stop beats two, obtained by sampling curves from the 90% band and counting which plan wins.',
      '<b>Live comparison.</b> As laps arrive, the current stint\'s slope is re-estimated and compared with the forecast band; the band shrinks as laps accumulate, which is the live confidence. Alerts fire when a measured quantity leaves its band: stint slope outside the Friday band, energy trend rising, cliff proximity, degraded feed. Each alert carries its evidence and a false-alarm rate computed from history.',
      '<b>Action list.</b> Ranked by seconds under the cost model, each with what it costs if wrong: pit now, stay out to lap N, switch to the two-stop. A strategist can argue with a number.',
      '<b>Driver in the loop.</b> The objective version is the push profile, measured. The subjective version is a structured input, axle, symptom, severity, that widens or narrows the band and can override a withheld compound. Team radio mining is a post-event item.',
      '<b>Tyre-change effects in the replay.</b> Pit-lane time by circuit, the age reset, the compound offset from qualifying, and the out-lap penalty measured from race stints. Track position needs rivals\' gaps and stays out of scope.',
      '<b>Not reinforcement learning.</b> The pit decision under our model is a small search solved exactly, so there is nothing for an agent to learn that enumeration does not give; "learning from mistakes on history" is what leave-one-weekend-out and the Sunday-night update already do, in a checkable form. Reinforcement learning earns its place only with a stochastic simulator with safety cars, rivals and traffic; a December 2025 paper does exactly that and it sits on the post-event roadmap with that citation.']) + [
      P('An expert system versus a scored system', H2),
      P('A previous winning engine in this space is built as a five-parameter formula calibrated at one circuit, an eighteen-rule alert catalogue with priority logic, and a seventeen-step next-best-action ladder. Every threshold in such a system is a human guess, the formula is fitted where it was fitted, and nothing says it was scored on a race it had not seen. Ours differs on four counts, and each is checkable: validation on 29 held-out cases across eleven circuits instead of calibration at one; alerts that are statistical tests against a forecast band instead of thresholds; actions ranked by seconds and probability instead of a ladder; and refusal of the quantities that cannot be observed instead of formulas wearing physical units. A learned curve shape is not what beats a formula; a scored system is.')]
# ---------------- 7 real-life data required ----------------
S += [PageBreak(), P('7. Real-life data required: what private feeds would add (scalability)', H1),
      P('Everything above runs on public data. The feeds below exist inside teams, the FIA or Pirelli, and would plug into the same estimator without changing the method. The improvement column is an engineering estimate with its basis stated; none of these numbers has been measured, because we do not have the data.', SM),
      table([['Data', 'Who has it', 'What it replaces or adds', 'Expected improvement (estimate)', 'Basis'],
             ['Fuel mass per lap', 'Teams (FIA-mandated fuel-flow meter)', 'Replaces the 1.1 kg/lap, 0.030 s/kg prior with a measurement', 'Headline error moves by at most 0.004 s/lap; the real gain is identifiability at low-degradation circuits: 3 to 5 of the 13 withheld compounds become issuable', 'The sensitivity sweep bounds the headline (0.021 to 0.027); 7 of 13 withheld cases are negative-slope cases where fuel and push are collinear'],
             ['Practice run plans: starting fuel, engine mode, push instructions per run', 'Teams', 'Turns the second lie, Sunday management, from a learned factor into a measured input', 'Medium-tyre error from 0.017 toward the lap-noise floor of about 0.010; about a third to a half of the remaining gap', 'Push profile already explains a median 52% of the Friday-to-Sunday gap from telemetry alone; instructions would explain most of the rest'],
             ['Tyre pressures and temperatures', 'Teams (FIA standard TPMS and infrared sensors), Pirelli', 'Thermal regime per lap: graining, blistering, overheating; per-lap temperature covariate; live sensor input', 'Bands 20 to 30% narrower; cliff lap predictable to about 2 laps where a cliff exists; live alerts on the same lap instead of 2 to 3 laps later', 'Temperature is the largest unmodelled per-lap covariate; the shape split (15 accelerating, 15 settling) is what temperature regime would explain'],
             ['Tread depth after runs', 'Pirelli, shared with teams', 'Calibrates pace loss to physical wear; enables the remaining-depth quantity we currently refuse', 'Enables a quantity, not an accuracy gain on pace; useful-life estimates on wear-limited circuits (Barcelona, Suzuka) become physical', 'No public analogue exists'],
             ['Aero map and downforce level per lap', 'Teams', 'Separates grip from vertical load in the grip index', 'Grip index becomes a true friction coefficient; corner-level degradation map', 'Apex speed squared measures grip times load; the map divides out the load'],
             ['Tyre set history: new or used, heat cycles, mileage', 'Pirelli allocation sheets, teams', 'Exact tyre age and condition on scrubbed sets used in Friday runs', 'A few percent on Friday slopes; fewer runs dropped for ambiguous age', 'FastF1 tyre life on reused sets is approximate'],
             ['Structured driver feedback and radio logs', 'Teams', 'Covariate for withheld decisions and band width', 'Qualitative: fewer wrong withheld calls on new circuits', 'Madrid medium is the live example of a case a driver would explain in one sentence'],
             ['Live sensor stream during the race', 'Teams', 'Feeds race-day mode with temperatures and pressures alongside lap times', 'Alert latency from 2 to 3 laps to the same lap; earlier pit calls', 'Lap-time-based detection needs several laps to separate slope from noise']], [3 * cm, 2.6 * cm, 3.6 * cm, 4.2 * cm, 3.4 * cm]),
      P('The scalability argument in one paragraph: the method is a measurement-and-validation loop, not a formula. Every private feed above replaces an assumption with a measurement and leaves the loop unchanged, so a team with full data runs the same code with tighter bands, and a junior series with timing only runs it with wider ones. That is why it scales up to a Formula 1 pit wall and down to Formula 2 without a rewrite.')]

# ---------------- 5 questions ----------------
QA = [
 ('The 2026 cars are new: fifty-fifty electric power, active aero, narrower tyres. Does a method tuned on 2026 mean anything?', 'The method is not tuned on 2026; it is a set of stated priors and measured corrections that apply to any season. What is 2026-specific is the learned transfer factor, and that is exactly why 2023 to 2025 are on disk: if the medium\'s Sunday ratio repeats at the same circuits across seasons it is a property of the tyre and the circuit; if it does not, it is a property of the 2026 car, and we say which.'),
 ('How can a fixed effect per stint separate the tyre from the car when the car changes setup between runs?', 'It cannot separate levels, and it does not try: each run\'s level is absorbed. Only the change within a run, lap over lap, informs the slope, and setup does not change mid-run. What a setup change can do is alter how fast the tyre degrades, and that becomes part of the spread between runs that the standard error reports.'),
 ('Your energy proxy uses position data at 3.7 Hz. Is curvature from that even meaningful?', 'Raw curvature from 3.7 Hz points is not, which is why we resample the path onto a uniform 10 m grid after removing stale repeated samples, smooth, and clip the radius at 15 m. The check is empirical: energy per lap is stable across drivers on the same compound, rises when a driver ramps up, and the coefficient linking it to lap time has a consistent scale between Friday and Sunday. Where the feed is degraded, Hungary race, China FP1, the counters catch it and the proxy is refused.'),
 ('Is the push adjustment not circular? Drivers lift because the tyre is going off.', 'Partly, yes, which is why the push-adjusted slope is a diagnostic and a second opinion, never the headline predictor. The as-driven estimator with the learned factor predicts the race better. The diagnostic\'s value is explanatory: it tells you why a Friday shows no signal and it accounts for about half of the Friday-to-Sunday gap.'),
 ('Why not a Bayesian hierarchical model, as your idea submission promised?', 'Because with eleven weekends the honest first step is the simplest estimator that validates, and it validates. The hierarchical layer is exactly what the three-season download is for: partial pooling of the transfer factor by compound across seasons, with a coverage check on the bands. It is on the roadmap for after the event, not because it is hard, but because it should be built on more than one season.'),
 ('Where could information leak from the race into the Friday prediction?', 'Three places, all closed. The transfer factor for a weekend is computed from other weekends only. The fallback value is the median of other weekends\' withheld outcomes. Compound offsets come from that weekend\'s qualifying, which precedes the race. The only thing that sees the race is the scorecard.'),
 ('Would this work in Formula 2, where there is no telemetry feed?', 'The estimator needs lap times, tyre age and compound, and flags, which F2 timing provides; fuel and evolution corrections carry over. What is lost without telemetry is the traffic flag and the push proxy, so more laps would be withheld and the bands would widen. That is the honest degraded mode, and it is still far better than a straight line.'),
 ('What happens when Pirelli brings different compounds to a circuit next year?', 'The curve is per compound name at that weekend, learned from that weekend\'s Friday; the transfer factor is per compound role, soft, medium, hard, which is about how drivers treat the role. If the role changes, the agreement rule notices the ratios disagree and stops applying the factor until enough weekends agree again.'),
 ('Half your withheld cases are hard tyres with too few Friday laps. Is that a method problem or a data problem?', 'A data problem that the method reports rather than hides: teams rarely run the hard on Friday at European rounds. The fallback still gives a forecast, and the practice-to-sprint test on sprint weekends adds a second observation of the hard. A team with its own Friday plan could fix it in an afternoon by running the hard.'),
 ('If you had one more day, what would you build first?', 'The per-driver degradation and push profile, teammate against teammate, checked for repeatability across weekends. It answers a question strategists and broadcasters actually ask, who looks after their tyres, and it needs nothing we do not already have.'),
 ('You say live monitoring, but the race starts after the event closes. What are you actually showing?', 'A lap-by-lap replay of a race we have already scored, Monza or Hungary: the Friday forecast on screen, then the live estimator updating at lap 10, 20 and 30, the band shrinking, the alerts firing or not, and the pit call moving or holding. The same code runs on Madrid on Sunday evening from the live-timing stream; the forecast it will be compared against is hashed before the race.'),
 ('Without tyre sensors, how early can your live mode detect a tyre going off?', 'From lap times alone it needs a few laps to separate a change in slope from lap noise, so two to three laps after the change. With a team\'s temperature and pressure feed the same alert fires on the lap it happens. That latency difference is exactly why the sensor socket is in the design.'),
 ('Why is a five-parameter formula calibrated at Bahrain worse than what you do?', 'Because a calibration is not a validation. A formula fitted at one circuit has no measured error anywhere else, and every alert threshold around it is a human guess. We report the error on 29 held-out cases across eleven circuits and fire alerts only when a measurement leaves a forecast band. If they show an out-of-sample error, we will compare it gladly.'),
 ('Why not reinforcement learning for the pit decision?', 'The decision under our cost model is a small search we solve exactly, so an agent has nothing to learn beyond the enumeration. Learning from history is already done by leave-one-weekend-out and the Sunday-night update, in a form a juror can check. Reinforcement learning becomes worth it with a stochastic race simulator, safety cars, rivals, traffic; a December 2025 paper does that, and it is on our post-event roadmap with that citation.')]
S += [PageBreak(), P('8. Fourteen questions a jury will ask, with answers', H1)]
for i, (q, a) in enumerate(QA, 1): S += [KeepTogether([P(f'<b>{i}. {q}</b>', B), P(a)])]
md('## 8. Fourteen jury questions\n' + '\n'.join(f'**{i}. {q}**\n\n{a}\n' for i, (q, a) in enumerate(QA, 1)))
doc = SimpleDocTemplate('out/Orb_v1_The_Case.pdf', pagesize=A4, leftMargin=1.9 * cm, rightMargin=1.9 * cm, topMargin=1.7 * cm, bottomMargin=1.7 * cm, title='Orb v1: the case', author='Team Orb v1')
def footer(c, d): c.saveState(); c.setFont('Helvetica', 7.5); c.setFillColor(colors.HexColor('#6B7280')); c.drawString(1.9 * cm, 1 * cm, f'Orb v1: the case · numbers from lock {L["generated_at"]}'); c.drawRightString(A4[0] - 1.9 * cm, 1 * cm, str(d.page)); c.restoreState()
doc.build(S, onFirstPage=footer, onLaterPages=footer); open('out/THE_CASE.md', 'w').write('\n'.join(MD)); print('built')
