"""Time-warped ghost: t_cf(S) = t_actual(S) + Delta(S), inverted to s(t), with the pit-lane switch (roadmap v5 task 0.5).

Inputs: a DriverTrajectory (actual world), the track and pit lane, and a CounterfactualLaps table (Workstream 2's per-lap
deltas: lap, lap_delta, cumulative_delta, pit_state, optional quantile columns or whole-curve samples; or a FIXTURE).

Ghost schedule, lap by lap (D_k = T_k + delta_k, so cumulative deltas are exact at every lap boundary):
    follow      the ghost keeps the actual lap's own time-distance shape, scaled to D_k: the delta is spread uniformly in
                lap-time fraction (a constant relative pace offset within the lap). This is the SAFE version; a tyre-demand
                weighted spread (more of the delta in the high-load sectors) is documented as future work in PERF.md.
    reference   an actual stop the counterfactual does not make: the ghost flies past on the driver's median clean-lap profile
    pit pair    a counterfactual stop the actual did not make: on-track parts on the reference profile, the pit lane on the
                driver's own recorded transit (time-shifted; the event median when the driver has no normal stop), the on-track
                time scaled so D_p + D_{p+1} is honoured exactly (kappa reported; a kappa far from 1 means the deltas do not
                carry the pit loss)
    same-lap stop in both worlds: follow, the ghost also uses the pit lane
Quantiles: whole-curve samples when present (each sample warps the whole race, then per-frame quantiles of position), else
the q10/q90 lap-delta columns as two curves. q10/q90 name the ELAPSED-DELTA quantiles (Workstream 2's convention: negative =
faster), so S_cf_q10 >= S_cf_median >= S_cf_q90 along the track; ordering is enforced and violations counted.
Frames at 1 Hz: t, s_actual, s_cf_median, s_cf_q10, s_cf_q90 (+ unwrapped S), laps, compounds, tyre ages, time_delta_s
(gap at the actual car's position, positive = ghost behind), distance_delta_m (positive = ghost ahead), pit flags and
pit-lane progress, track status; compressed float32 with a sha256 sidecar.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from replay import io as rio
from replay.geometry import TrackPath, PitLane
from replay.sources import COMPOUND_CODE, CODE_COMPOUND
from replay.trajectory import DriverTrajectory, first_arrival_inverse

PIT_LOSS_FIXTURE_S = 22.0
FIXTURE_LABEL = 'FIXTURE: synthetic per-lap deltas generated by replay.timewarp.fixture_laps (Workstream 2 counterfactual output not present)'
KAPPA_WARN = (0.6, 1.6)


# ---------------------------------------------------------------- counterfactual laps table

def stints_to_lap_map(stints: list[dict], n_laps: int) -> tuple[dict[int, str], dict[int, int]]:
    """{lap: compound}, {lap: tyre_age} from [{compound, first_lap, last_lap}] (age 1 on the first lap of a stint)."""
    comp, age = {}, {}
    for st in stints:
        for k in range(int(st['first_lap']), int(st['last_lap']) + 1):
            comp[k] = str(st['compound']).upper(); age[k] = k - int(st['first_lap']) + 1
    last_c = comp.get(max(comp) if comp else 1, 'UNKNOWN'); last_first = max((int(s['first_lap']) for s in stints), default=1)
    for k in range(1, n_laps + 1):
        if k not in comp:
            comp[k] = last_c; age[k] = k - last_first + 1
    return comp, age


def plan_to_stints(plan: dict) -> list[dict]:
    """Lock-style plan {stints: [{compound, laps}], pit_laps} -> [{compound, first_lap, last_lap}]."""
    out, k = [], 1
    for st in plan['stints']:
        n = int(st['laps'])
        out.append(dict(compound=str(st['compound']).upper(), first_lap=k, last_lap=k + n - 1))
        k += n
    return out


def stints_from_trajectory(traj: DriverTrajectory) -> tuple[list[dict], list[int]]:
    """Actual stints and in-laps from the recorded lap table."""
    lt = traj.laps
    stints = []
    for st, g in lt.groupby('stint', sort=True):
        stints.append(dict(compound=str(g['compound'].iloc[0]).upper(), first_lap=int(g['lap'].min()), last_lap=int(g['lap'].max())))
    pit_laps = [int(x) for x in lt.loc[lt['pit_in'].astype(bool), 'lap']]
    return stints, pit_laps


@dataclass
class CounterfactualLaps:
    lap: np.ndarray
    lap_delta: np.ndarray
    cumulative_delta: np.ndarray
    pit_state: list[str]
    actual_pit_laps: list[int]
    cf_pit_laps: list[int]
    actual_stints: list[dict]
    cf_stints: list[dict]
    lap_delta_q10: Optional[np.ndarray] = None
    lap_delta_q90: Optional[np.ndarray] = None
    samples: Optional[np.ndarray] = None          # (n_samples, n_laps) whole-curve lap deltas
    source: str = 'workstream2'
    label: str = ''
    scenario_id: str = ''
    meta: dict = field(default_factory=dict)

    @property
    def n_laps(self) -> int:
        return int(self.lap.max()) if len(self.lap) else 0

    def delta_map(self, which: str = 'median') -> dict[int, float]:
        arr = {'median': self.lap_delta, 'q10': self.lap_delta_q10, 'q90': self.lap_delta_q90}[which]
        if arr is None:
            arr = self.lap_delta
        return {int(k): float(v) for k, v in zip(self.lap, arr)}

    def is_identity(self) -> bool:
        return bool(np.allclose(self.lap_delta, 0.0) and sorted(self.actual_pit_laps) == sorted(self.cf_pit_laps))

    def to_dict(self) -> dict:
        return dict(scenario_id=self.scenario_id, source=self.source, label=self.label, lap=self.lap.astype(int).tolist(), lap_delta=np.round(self.lap_delta, 4).tolist(),
                    cumulative_delta=np.round(self.cumulative_delta, 4).tolist(), pit_state=list(self.pit_state), actual_pit_laps=list(self.actual_pit_laps), cf_pit_laps=list(self.cf_pit_laps),
                    actual_stints=self.actual_stints, cf_stints=self.cf_stints, lap_delta_q10=None if self.lap_delta_q10 is None else np.round(self.lap_delta_q10, 4).tolist(),
                    lap_delta_q90=None if self.lap_delta_q90 is None else np.round(self.lap_delta_q90, 4).tolist(), n_samples=0 if self.samples is None else int(len(self.samples)), meta=self.meta)


def from_table(table, actual_plan: dict | list[dict], cf_plan: dict | list[dict], scenario_id: str = '', source: str = 'workstream2', label: str = '', n_laps: Optional[int] = None,
               samples: Optional[np.ndarray] = None, actual_pit_laps: Optional[list[int]] = None, cf_pit_laps: Optional[list[int]] = None) -> CounterfactualLaps:
    """Workstream 2's laps table (DataFrame / list of records / dict of columns with lap, lap_delta, cumulative_delta, pit_state and
    optional lap_delta_q10 / lap_delta_q90 or cumulative_delta_q10 / cumulative_delta_q90) plus the two plans (lock-style
    {stints, pit_laps} or [{compound, first_lap, last_lap}])."""
    df = pd.DataFrame(table)
    if 'lap' not in df.columns:
        raise ValueError('laps table needs a lap column')
    df = df.sort_values('lap').reset_index(drop=True)
    lap = df['lap'].to_numpy(dtype=int)
    if 'lap_delta' in df.columns:
        ld = df['lap_delta'].to_numpy(dtype=float)
    elif 'delta_s' in df.columns:                                        # fixtures/sidecars/cf_*_lap_deltas.json records
        ld = df['delta_s'].to_numpy(dtype=float)
    elif 'cumulative_delta' in df.columns:
        ld = np.diff(np.concatenate([[0.0], df['cumulative_delta'].to_numpy(dtype=float)]))
    else:
        raise ValueError('laps table needs lap_delta (or delta_s / cumulative_delta)')
    ld = np.nan_to_num(ld, nan=0.0)
    cum = df['cumulative_delta'].to_numpy(dtype=float) if 'cumulative_delta' in df.columns else np.cumsum(ld)
    pit_state = [str(x) for x in df['pit_state']] if 'pit_state' in df.columns else ['none'] * len(df)
    q10 = q90 = None
    # the halo needs the whole-curve quantiles of the CUMULATIVE delta (Workstream 2 samples whole curves); per-lap increment
    # quantiles summed over laps over-state the spread, so they are only the fallback
    if 'cumulative_delta_q10' in df.columns and 'cumulative_delta_q90' in df.columns:
        q10 = np.diff(np.concatenate([[0.0], np.nan_to_num(df['cumulative_delta_q10'].to_numpy(dtype=float))])); q90 = np.diff(np.concatenate([[0.0], np.nan_to_num(df['cumulative_delta_q90'].to_numpy(dtype=float))]))
    elif 'lap_delta_q10' in df.columns and 'lap_delta_q90' in df.columns:
        q10 = np.nan_to_num(df['lap_delta_q10'].to_numpy(dtype=float)); q90 = np.nan_to_num(df['lap_delta_q90'].to_numpy(dtype=float))
    n = int(n_laps or lap.max())
    a_st = plan_to_stints(actual_plan) if isinstance(actual_plan, dict) else list(actual_plan)
    c_st = plan_to_stints(cf_plan) if isinstance(cf_plan, dict) else list(cf_plan)
    a_pits = list(actual_plan.get('pit_laps', [])) if isinstance(actual_plan, dict) else (actual_pit_laps if actual_pit_laps is not None else [s['last_lap'] for s in a_st[:-1]])
    c_pits = list(cf_plan.get('pit_laps', [])) if isinstance(cf_plan, dict) else (cf_pit_laps if cf_pit_laps is not None else [s['last_lap'] for s in c_st[:-1]])
    # pit_state may also name the counterfactual in-laps
    named = [int(k) for k, st in zip(lap, pit_state) if st.lower() in ('in', 'in_lap', 'pit_in', 'stop', 'box')]
    if named and not c_pits:
        c_pits = named
    return CounterfactualLaps(lap=lap, lap_delta=ld, cumulative_delta=cum, pit_state=pit_state, actual_pit_laps=[int(x) for x in a_pits], cf_pit_laps=[int(x) for x in c_pits],
                              actual_stints=a_st, cf_stints=c_st, lap_delta_q10=q10, lap_delta_q90=q90, samples=None if samples is None else np.asarray(samples, dtype=float),
                              source=source, label=label, scenario_id=scenario_id, meta=dict(n_laps=n))


def identity_laps(traj: DriverTrajectory, label: str = 'identity: counterfactual plan == actual plan, zero deltas') -> CounterfactualLaps:
    stints, pits = stints_from_trajectory(traj)
    n = traj.n_laps
    lap = np.arange(1, n + 1)
    return CounterfactualLaps(lap=lap, lap_delta=np.zeros(n), cumulative_delta=np.zeros(n), pit_state=['none'] * n, actual_pit_laps=pits, cf_pit_laps=list(pits), actual_stints=stints, cf_stints=list(stints),
                              source='identity', label=label, scenario_id='identity', meta=dict(n_laps=n))


def fixture_laps(traj: DriverTrajectory, intervention_lap: int, to_compound: str, seed: int = 2026, n_samples: int = 200, pit_loss_s: float = PIT_LOSS_FIXTURE_S,
                 scenario_id: str = '') -> CounterfactualLaps:
    """FIXTURE counterfactual: the recorded plan up to intervention_lap - 1, a stop on intervention_lap, to_compound to the flag.
    Synthetic deltas from a toy pace model (compound offset + linear degradation + pit loss + warm-up); whole-curve samples from
    seeded perturbations of the degradation rates and the pit loss. Labelled FIXTURE everywhere it is displayed."""
    rng = np.random.default_rng(seed)
    n = traj.n_laps
    a_st, a_pits = stints_from_trajectory(traj)
    p = int(np.clip(intervention_lap, 1, n - 1))
    c_st = []
    for st in a_st:
        if st['last_lap'] < p:
            c_st.append(dict(st))
        elif st['first_lap'] <= p:
            c_st.append(dict(compound=st['compound'], first_lap=st['first_lap'], last_lap=p))
    if not c_st:
        c_st = [dict(compound=a_st[0]['compound'], first_lap=1, last_lap=p)]
    c_st.append(dict(compound=str(to_compound).upper(), first_lap=p + 1, last_lap=n))
    c_pits = [pl for pl in a_pits if pl < p] + [p]
    a_comp, a_age = stints_to_lap_map(a_st, n); c_comp, c_age = stints_to_lap_map(c_st, n)
    deg = dict(SOFT=0.060, MEDIUM=0.035, HARD=0.020, INTERMEDIATE=0.05, WET=0.05, UNKNOWN=0.035)
    offset = dict(SOFT=0.0, MEDIUM=0.30, HARD=0.60, INTERMEDIATE=2.0, WET=4.0, UNKNOWN=0.3)
    laps = np.arange(1, n + 1)
    added = sorted(set(c_pits) - set(a_pits)); removed = sorted(set(a_pits) - set(c_pits))

    def curve(deg_mult: dict[str, float], pit_loss: float) -> np.ndarray:
        d = np.zeros(n)
        for k in laps:
            ca, cc = a_comp[k], c_comp[k]
            pace_a = offset[ca] + deg[ca] * deg_mult[ca] * a_age[k]
            pace_c = offset[cc] + deg[cc] * deg_mult[cc] * c_age[k]
            d[k - 1] = pace_c - pace_a
            if k in added:
                d[k - 1] += 0.6 * pit_loss
            if k - 1 in added:
                d[k - 1] += 0.4 * pit_loss + 0.4
            if k in removed:
                d[k - 1] -= 0.6 * pit_loss
            if k - 1 in removed:
                d[k - 1] -= 0.4 * pit_loss + 0.4
        return d
    base_mult = {c: 1.0 for c in deg}
    median_curve = curve(base_mult, pit_loss_s)
    samples = np.empty((n_samples, n))
    for i in range(n_samples):
        mult = {c: float(np.exp(rng.normal(0.0, 0.25))) for c in deg}
        samples[i] = curve(mult, float(rng.normal(pit_loss_s, 1.5)))
    cum_s = np.cumsum(samples, axis=1)
    q10c = np.quantile(cum_s, 0.1, axis=0); q90c = np.quantile(cum_s, 0.9, axis=0)
    q10 = np.diff(np.concatenate([[0.0], q10c])); q90 = np.diff(np.concatenate([[0.0], q90c]))
    pit_state = ['in' if k in c_pits else ('out' if k - 1 in c_pits else 'none') for k in laps]
    sid = scenario_id or f'FIXTURE_{traj.event}_{traj.driver}_stop{p}_{str(to_compound).upper()}'
    return CounterfactualLaps(lap=laps, lap_delta=median_curve, cumulative_delta=np.cumsum(median_curve), pit_state=pit_state, actual_pit_laps=a_pits, cf_pit_laps=c_pits, actual_stints=a_st, cf_stints=c_st,
                              lap_delta_q10=q10, lap_delta_q90=q90, samples=samples, source='FIXTURE', label=FIXTURE_LABEL, scenario_id=sid,
                              meta=dict(n_laps=n, intervention_lap=p, to_compound=str(to_compound).upper(), seed=seed, n_samples=n_samples, pit_loss_s=pit_loss_s, toy_model=dict(deg=deg, offset=offset)))


# ---------------------------------------------------------------- ghost construction

def actual_lap_boundaries(traj: DriverTrajectory) -> tuple[np.ndarray, float]:
    """t_cross[k-1] = time the actual car reaches S = (k-1) L (lap 1: the timing start); plus the finish time t(S_end)."""
    L = traj.L; n = traj.n_laps
    t_cross = np.empty(n)
    t_cross[0] = float(traj.laps['t_start'].iloc[0]) if np.isfinite(traj.laps['t_start'].iloc[0]) else float(traj.t[0])
    if n > 1:
        t_cross[1:] = traj.t_of_S(np.arange(1, n) * L)
    t_fin = float(traj.t_of_S(traj.S_end)[0])
    t_cross = np.maximum.accumulate(np.concatenate([t_cross, [max(t_fin, t_cross[-1] + 1.0)]]))
    return t_cross[:-1], float(t_cross[-1])


def reference_profile(traj: DriverTrajectory, track: TrackPath, t_cross: np.ndarray, t_fin: float) -> tuple[np.ndarray, np.ndarray, float, int]:
    """(sigma grid, phi_ref(sigma), T_ref, n laps used): median clean-lap time fraction vs distance fraction."""
    L = traj.L; n = len(t_cross)
    ends = np.concatenate([t_cross[1:], [t_fin]])
    T = ends - t_cross
    lt = traj.laps.set_index('lap')
    clean = []
    for k in range(2, n + 1):
        row = lt.loc[k] if k in lt.index else None
        ok = row is not None and bool(row['accurate']) and bool(row['green']) and not bool(row['pit_in']) and not bool(row['pit_out'])
        if ok and T[k - 1] > 0:
            clean.append(k)
    if len(clean) < 3:
        cand = [k for k in range(2, n + 1) if T[k - 1] > 0]
        tmin = min((T[k - 1] for k in cand), default=1.0)
        clean = [k for k in cand if T[k - 1] <= 1.3 * tmin] or cand
    sigma = np.concatenate([track.s / L, [1.0]])
    profiles = []
    for k in clean:
        S_q = (k - 1) * L + sigma * L
        tq = traj.t_of_S(S_q)
        profiles.append((tq - t_cross[k - 1]) / T[k - 1])
    if not profiles:
        phi = sigma.copy()
        return sigma, phi, float(T[T > 0].min()) if (T > 0).any() else 90.0, 0
    phi = np.median(np.vstack(profiles), axis=0)
    phi = np.maximum.accumulate(np.clip(phi, 0.0, 1.0))
    phi = (phi - phi[0]) / max(phi[-1] - phi[0], 1e-9)
    T_ref = float(np.median([T[k - 1] for k in clean]))
    return sigma, phi, T_ref, len(clean)


def lap_kinds(n: int, actual_pits: list[int], cf_pits: list[int]) -> list[str]:
    kinds = ['follow'] * (n + 1)      # 1-based
    a, c = set(actual_pits), set(cf_pits)
    for k in range(1, n + 1):
        if kinds[k] not in ('follow',):
            continue
        if k in c and k in a:
            continue
        if k in c:
            if k + 1 <= n:
                kinds[k] = 'pit_in'; kinds[k + 1] = 'pit_out'
            else:
                kinds[k] = 'reference'
        elif k in a:
            kinds[k] = 'reference'
            if k + 1 <= n and kinds[k + 1] == 'follow' and (k + 1) not in c:
                kinds[k + 1] = 'reference'
    return kinds[1:]


def _transit(traj: DriverTrajectory, pitlane: PitLane) -> tuple[np.ndarray, np.ndarray, str]:
    """The driver's own recorded stop when it is a normal one (no red flag, duration within 0.6-1.6x the event median), else the event median."""
    ref = pitlane.transit_time if np.isfinite(pitlane.transit_time) and pitlane.transit_time > 0 else 30.0
    for st in traj.stops:
        if st.get('normal') and not st.get('red_flag') and len(st['tau']) >= 3 and st['s_pit'][-1] >= 0.5 * pitlane.length and 0.6 * ref <= st['duration'] <= 1.6 * ref:
            tau = np.asarray(st['tau'], dtype=float); sp = np.asarray(st['s_pit'], dtype=float)
            sp = np.maximum.accumulate(np.clip(sp, 0.0, pitlane.length)); sp[-1] = pitlane.length; sp[0] = 0.0
            return tau, sp, f"driver's recorded stop (lap {st['lap_in']}, {tau[-1]:.1f} s), time-shifted"
    return np.asarray(pitlane.transit_tau, dtype=float), np.asarray(pitlane.transit_s, dtype=float), f'event median transit ({pitlane.source} pit lane, {pitlane.transit_time:.1f} s)'


def ghost_curve(traj: DriverTrajectory, track: TrackPath, pitlane: PitLane, deltas: dict[int, float], cf_pits: list[int], actual_pits: list[int],
                t_cross: np.ndarray, t_fin: float, sigma: np.ndarray, phi: np.ndarray, T_ref: float) -> dict:
    """Piecewise (S, t_cf) curve of the ghost plus its pit segments [(S_entry, S_exit, s_pit_of_S)] and per-lap notes."""
    L = traj.L; n = len(t_cross)
    ends = np.concatenate([t_cross[1:], [t_fin]]); T = ends - t_cross
    kinds = lap_kinds(n, actual_pits, cf_pits)
    S_pts: list[np.ndarray] = []; t_pts: list[np.ndarray] = []
    pit_segments: list[dict] = []; notes: list[dict] = []
    t_start_cf = float(t_cross[0])
    entry_s, exit_s = float(pitlane.entry_s), float(pitlane.exit_s)
    sig_entry = entry_s / L; sig_exit = exit_s / L
    tau_t, sp_t, transit_src = _transit(traj, pitlane)
    k = 1
    S_end = traj.S_end
    while k <= n:
        kind = kinds[k - 1]
        D = T[k - 1] + deltas.get(k, 0.0)
        note = dict(lap=k, kind=kind, T_actual=round(float(T[k - 1]), 3), delta=round(float(deltas.get(k, 0.0)), 4), t_start_actual=round(float(t_cross[k - 1]), 3), t_start_cf=round(t_start_cf, 3))
        if D < 0.2 * T[k - 1]:
            note['warning'] = f'D_cf clamped from {D:.2f} to {0.2 * T[k - 1]:.2f} s'; D = 0.2 * T[k - 1]
        S0 = (k - 1) * L
        sig0 = 0.0
        if k == 1:                                   # the race starts where the car is at the start signal (grid box / rolling), not on the line
            S0 = float(np.clip(traj.S_of_t(t_cross[0])[0], 0.0, 0.5 * L)); sig0 = S0 / L
        phi0 = float(np.interp(sig0, sigma, phi))
        phi_k = lambda sg: (np.interp(sg, sigma, phi) - phi0) / max(1.0 - phi0, 1e-9)      # reference profile re-based at sig0
        if kind == 'pit_in':
            D2 = T[k] + deltas.get(k + 1, 0.0)
            D_pair = D + D2
            tau_pit = float(tau_t[-1])
            F_on = float(phi_k(sig_entry) + (1.0 - np.interp(sig_exit, sigma, phi)))
            kappa = (D_pair - tau_pit) / max(T_ref * F_on, 1e-6)
            note.update(kind='pit_pair', D_pair=round(float(D_pair), 3), tau_pit=round(tau_pit, 2), kappa=round(float(kappa), 4), transit=transit_src)
            if not (KAPPA_WARN[0] <= kappa <= KAPPA_WARN[1]):
                note['warning'] = f'kappa {kappa:.2f} outside {KAPPA_WARN}: the lap deltas do not carry a plausible pit loss'
            kappa = float(np.clip(kappa, 0.05, 5.0))
            # on-track part of the in-lap
            m = (sigma < sig_entry) & (sigma >= sig0)
            sig_a = np.concatenate([[sig0], sigma[m], [sig_entry]]) if sig0 > 0 else np.concatenate([sigma[m], [sig_entry]])
            S_a = (k - 1) * L + sig_a * L; t_a = t_start_cf + kappa * T_ref * phi_k(sig_a)
            t_entry_cf = float(t_a[-1])
            # pit lane, mapped linearly onto the track distance between the junctions
            S_entry = S0 + entry_s; S_exit = k * L + exit_s
            S_p = S_entry + (sp_t / max(pitlane.length, 1e-6)) * (S_exit - S_entry); t_p = t_entry_cf + tau_t
            pit_segments.append(dict(S_entry=float(S_entry), S_exit=float(S_exit), lap_in=k, t_entry=t_entry_cf, t_exit=float(t_p[-1]), S_map=S_p.tolist(), s_pit_map=sp_t.tolist()))
            # on-track part of the out-lap
            m2 = sigma > sig_exit
            sig_b = np.concatenate([[sig_exit], sigma[m2]])
            S_b = k * L + sig_b * L; t_b = t_p[-1] + kappa * T_ref * (np.interp(sig_b, sigma, phi) - np.interp(sig_exit, sigma, phi))
            S_pts += [S_a, S_p[1:], S_b[1:]]; t_pts += [t_a, t_p[1:], t_b[1:]]
            notes.append(note)
            notes.append(dict(lap=k + 1, kind='pit_out', T_actual=round(float(T[k]), 3), delta=round(float(deltas.get(k + 1, 0.0)), 4), t_start_actual=round(float(t_cross[k]), 3), t_start_cf=None))
            t_start_cf = t_start_cf + D_pair
            k += 2
            continue
        if kind == 'follow':
            m = (traj.t >= t_cross[k - 1]) & (traj.t <= ends[k - 1])
            S_in = traj.S[m]; t_in = traj.t[m]
            S_seg = np.concatenate([[S0], S_in, [min(k * L, S_end)]]); t_seg = np.concatenate([[t_cross[k - 1]], t_in, [ends[k - 1]]])
            order = np.argsort(t_seg, kind='stable'); S_seg, t_seg = S_seg[order], t_seg[order]
            phi_k = (t_seg - t_cross[k - 1]) / max(T[k - 1], 1e-6)
            t_cf = t_start_cf + D * phi_k
            S_pts.append(S_seg); t_pts.append(t_cf)
            # same-lap stop in both worlds: the ghost uses the pit lane where the actual did
            for st in traj.stops:
                if int(st['lap_in']) == k and (k in cf_pits):
                    tt = st['t_entry'] + np.asarray(st['tau'], dtype=float)
                    S_map = traj.S_of_t(tt)
                    t_map = np.interp(S_map, S_seg, t_cf) if len(S_seg) > 1 else tt
                    pit_segments.append(dict(S_entry=float(S_map[0]), S_exit=float(S_map[-1]), lap_in=k, t_entry=float(t_map[0]), t_exit=float(t_map[-1]), S_map=S_map.tolist(), s_pit_map=np.asarray(st['s_pit'], dtype=float).tolist()))
                    note['pit'] = 'same-lap stop in both worlds: recorded pit lane'
        else:   # reference
            m = sigma >= sig0
            sig_r = np.concatenate([[sig0], sigma[m]]) if sig0 > 0 and sigma[m][0] > sig0 else sigma[m]
            S_seg = (k - 1) * L + sig_r * L; t_cf = t_start_cf + D * phi_k(sig_r)
            S_seg = np.minimum(S_seg, S_end) if k == n else S_seg
            S_pts.append(S_seg); t_pts.append(t_cf)
        notes.append(note)
        t_start_cf = t_start_cf + D
        k += 1
    S_all = np.concatenate(S_pts); t_all = np.concatenate(t_pts)
    order = np.argsort(t_all, kind='stable'); S_all, t_all = S_all[order], t_all[order]     # time-ordered: standstills (S plateaus) are kept
    S_all = np.maximum.accumulate(S_all)
    t_all = np.maximum.accumulate(t_all) + np.arange(len(t_all)) * 1e-7
    S_first, t_first = first_arrival_inverse(S_all, t_all)                                   # first time each distance is reached: t_cf(S)
    return dict(S=S_all, t=t_all, S_first=S_first, t_first=t_first, pit_segments=pit_segments, notes=notes, t_finish=float(t_all[-1]), kinds=kinds)


def _invert(curve: dict, tg: np.ndarray) -> np.ndarray:
    return np.interp(tg, curve['t'], curve['S'], left=curve['S'][0], right=curve['S'][-1])


# ---------------------------------------------------------------- frames

@dataclass
class Frames:
    arrays: dict[str, np.ndarray]
    meta: dict

    @property
    def n(self) -> int:
        return len(self.arrays['t'])

    def __getitem__(self, k: str) -> np.ndarray:
        return self.arrays[k]

    def save(self, path: str | Path) -> str:
        p = Path(path); p.parent.mkdir(parents=True, exist_ok=True)
        return rio.save_npz(p, meta=self.meta, **self.arrays)

    @classmethod
    def load(cls, path: str | Path) -> 'Frames':
        z = rio.load_npz(path)
        meta = z.pop('meta')
        return cls(arrays={k: np.asarray(v) for k, v in z.items()}, meta=meta)

    def to_player_dict(self) -> dict:
        a = self.arrays
        r1 = lambda k: np.round(a[k].astype(float), 1).tolist()
        r2 = lambda k: np.round(a[k].astype(float), 2).tolist()
        ints = lambda k: a[k].astype(int).tolist()
        pp = lambda k: [None if not np.isfinite(v) else round(float(v), 1) for v in a[k].astype(float)]
        return dict(t=ints('t'), S_actual=r1('S_actual'), S_cf=r1('S_cf'), S_cf_q10=r1('S_cf_q10'), S_cf_q90=r1('S_cf_q90'), lap_actual=ints('lap_actual'), lap_cf=ints('lap_cf'),
                    compound_actual=ints('compound_actual'), tyre_age_actual=ints('tyre_age_actual'), compound_cf=ints('compound_cf'), tyre_age_cf=ints('tyre_age_cf'),
                    time_delta_s=r2('time_delta_s'), distance_delta_m=r1('distance_delta_m'), act_pit=ints('act_pit'), cf_pit=ints('cf_pit'), act_pit_progress=pp('act_pit_progress'),
                    cf_pit_progress=pp('cf_pit_progress'), track_status=ints('track_status'), meta=self.meta)


def build_frames(traj: DriverTrajectory, track: TrackPath, pitlane: PitLane, cf: CounterfactualLaps, hz: float = 1.0, max_samples: int = 64) -> Frames:
    L = traj.L; n = traj.n_laps
    t_cross, t_fin = actual_lap_boundaries(traj)
    sigma, phi, T_ref, n_ref = reference_profile(traj, track, t_cross, t_fin)
    actual_pits_rec = [int(x) for x in traj.laps.loc[traj.laps['pit_in'].astype(bool), 'lap']]
    warnings = []
    if sorted(actual_pits_rec) != sorted(int(x) for x in cf.actual_pit_laps):
        warnings.append(f'recorded in-laps {actual_pits_rec} differ from the scenario actual_pit_laps {list(cf.actual_pit_laps)}; the recorded ones drive the ghost schedule')
    cf_pits = [int(x) for x in cf.cf_pit_laps]
    med = ghost_curve(traj, track, pitlane, cf.delta_map('median'), cf_pits, actual_pits_rec, t_cross, t_fin, sigma, phi, T_ref)
    t_end = max(float(traj.t[-1]), med['t_finish'])
    n_frames = int(np.ceil(t_end * hz)) + 1
    tg = np.arange(n_frames) / hz
    S_act = np.interp(tg, traj.t, traj.S, left=traj.S[0], right=traj.S[-1])
    S_cf = _invert(med, tg)
    # quantiles
    q_source = 'none'
    if cf.samples is not None and len(cf.samples) >= 5:
        samp = cf.samples if len(cf.samples) <= max_samples else cf.samples[np.linspace(0, len(cf.samples) - 1, max_samples).round().astype(int)]
        Ss = np.empty((len(samp), n_frames))
        for i, row in enumerate(samp):
            dmap = {int(k): float(v) for k, v in zip(cf.lap, row)}
            Ss[i] = _invert(ghost_curve(traj, track, pitlane, dmap, cf_pits, actual_pits_rec, t_cross, t_fin, sigma, phi, T_ref), tg)
        S_q10 = np.quantile(Ss, 0.9, axis=0); S_q90 = np.quantile(Ss, 0.1, axis=0)
        q_source = f'whole-curve sampling ({len(samp)} of {len(cf.samples)} samples): per-frame 90th / 10th percentile of ghost distance'
    elif cf.lap_delta_q10 is not None and cf.lap_delta_q90 is not None:
        S_q10 = _invert(ghost_curve(traj, track, pitlane, cf.delta_map('q10'), cf_pits, actual_pits_rec, t_cross, t_fin, sigma, phi, T_ref), tg)
        S_q90 = _invert(ghost_curve(traj, track, pitlane, cf.delta_map('q90'), cf_pits, actual_pits_rec, t_cross, t_fin, sigma, phi, T_ref), tg)
        q_source = 'per-lap q10 / q90 delta curves'
    else:
        S_q10 = S_cf.copy(); S_q90 = S_cf.copy()
    viol = int(((S_q10 < S_cf - 1e-6) | (S_q90 > S_cf + 1e-6)).sum())
    S_q10 = np.maximum(S_q10, S_cf); S_q90 = np.minimum(S_q90, S_cf)
    # per-frame quantities
    lap_pos = lambda S: np.clip(np.floor(np.maximum(S, 0.0) / L).astype(int) + 1, 1, n)
    lap_a = lap_pos(S_act); lap_c = lap_pos(S_cf)
    lt = traj.laps.set_index('lap')
    a_comp_lap = {int(k): int(lt.loc[k, 'compound_code']) for k in lt.index}; a_age_lap = {int(k): int(lt.loc[k, 'tyre_age']) for k in lt.index}
    c_comp_map, c_age_map = stints_to_lap_map(cf.cf_stints, n)
    lap_timing = np.clip(np.interp(tg, traj.t, traj.lap).round().astype(int), 1, n)
    comp_a = np.array([a_comp_lap.get(int(k), 0) for k in lap_timing], dtype=np.int8); age_a = np.array([a_age_lap.get(int(k), 0) for k in lap_timing], dtype=np.int16)
    comp_c = np.array([COMPOUND_CODE.get(c_comp_map.get(int(k), 'UNKNOWN'), 0) for k in lap_c], dtype=np.int8); age_c = np.array([c_age_map.get(int(k), 0) for k in lap_c], dtype=np.int16)
    # gap = difference of first-arrival times at the actual car's current position (both worlds on the same convention)
    Sa_first, ta_first = first_arrival_inverse(S_act, tg)
    time_delta = np.interp(S_act, med['S_first'], med['t_first'], left=med['t_first'][0], right=med['t_first'][-1]) - np.interp(S_act, Sa_first, ta_first)
    finished = S_act >= traj.S_end - 1e-6                      # after the flag the gap is the finish-time difference, not t_fin - t
    time_delta[finished] = med['t_finish'] - t_fin
    dist_delta = S_cf - S_act
    act_pit = np.interp(tg, traj.t, traj.in_pit.astype(float)) > 0.5
    act_prog = np.interp(tg, traj.t, np.nan_to_num(traj.pit_progress, nan=-1.0)); act_prog = np.where(act_pit & (act_prog >= 0), act_prog, np.nan)
    cf_pit = np.zeros(n_frames, dtype=bool); cf_prog = np.full(n_frames, np.nan)
    for seg in med['pit_segments']:
        m = (S_cf >= seg['S_entry']) & (S_cf <= seg['S_exit'])
        cf_pit |= m
        cf_prog[m] = np.interp(S_cf[m], np.asarray(seg['S_map']), np.asarray(seg['s_pit_map']))
    status = np.interp(tg, traj.t, traj.status.astype(float)).round().astype(np.int8) if traj.status is not None else np.zeros(n_frames, dtype=np.int8)
    sc_periods = []
    run = None
    for i, c in enumerate(status):
        kind = {4: 'SC', 5: 'RED', 6: 'VSC', 7: 'VSC'}.get(int(c))
        if kind and run and run[2] == kind:
            run[1] = float(tg[i])
        elif kind:
            if run: sc_periods.append(run)
            run = [float(tg[i]), float(tg[i]), kind]
        elif run:
            sc_periods.append(run); run = None
    if run: sc_periods.append(run)
    arrays = dict(t=tg, t_session=np.interp(tg, traj.t, traj.t_session), S_actual=S_act, s_actual=np.mod(np.maximum(S_act, 0.0), L), lap_actual=lap_a.astype(np.int16), lap_timing=lap_timing.astype(np.int16),
                  S_cf=S_cf, s_cf_median=np.mod(np.maximum(S_cf, 0.0), L), lap_cf=lap_c.astype(np.int16), S_cf_q10=S_q10, s_cf_q10=np.mod(np.maximum(S_q10, 0.0), L), S_cf_q90=S_q90, s_cf_q90=np.mod(np.maximum(S_q90, 0.0), L),
                  compound_actual=comp_a, tyre_age_actual=age_a, compound_cf=comp_c, tyre_age_cf=age_c, time_delta_s=time_delta, distance_delta_m=dist_delta,
                  act_pit=act_pit.astype(np.uint8), act_pit_progress=act_prog, cf_pit=cf_pit.astype(np.uint8), cf_pit_progress=cf_prog, track_status=status)
    notes = med['notes']
    for nt in notes:
        if 'warning' in nt:
            warnings.append(f"lap {nt['lap']}: {nt['warning']}")
    meta = dict(event=traj.event, driver=traj.driver, scenario_id=cf.scenario_id, source=cf.source, label=cf.label, L=round(L, 3), n_laps=n, n_frames=n_frames, hz=hz,
                cuts_session_s=traj.cuts, sc_periods=sc_periods, actual_pit_laps=actual_pits_rec, cf_pit_laps=cf_pits, actual_stints=cf.actual_stints, cf_stints=cf.cf_stints,
                pitlane_source=pitlane.source, pit_entry_s=round(float(pitlane.entry_s), 2), pit_exit_s=round(float(pitlane.exit_s), 2), quantile_source=q_source, quantile_order_violations=viol,
                finish_delta_s=round(float(med['t_finish'] - t_fin), 3), cumulative_delta_table_s=round(float(cf.cumulative_delta[-1]), 3) if len(cf.cumulative_delta) else None,
                spread='lap delta spread uniformly in lap-time fraction within the lap (safe version); tyre-demand weighting: future', reference_profile_laps=n_ref, T_ref_s=round(T_ref, 3),
                lap_table=notes, warnings=warnings, compound_codes=CODE_COMPOUND, sign_convention='time_delta_s > 0: ghost reaches the actual car\'s position later (behind); distance_delta_m > 0: ghost ahead',
                identity=cf.is_identity())
    return Frames(arrays=arrays, meta=meta)


__all__ = ['CounterfactualLaps', 'Frames', 'from_table', 'identity_laps', 'fixture_laps', 'stints_from_trajectory', 'plan_to_stints', 'stints_to_lap_map', 'lap_kinds',
           'actual_lap_boundaries', 'reference_profile', 'ghost_curve', 'build_frames', 'FIXTURE_LABEL']
